### ISSUE TITLE
Bug - example not working du to _whiting_jit 

### ISSUE THREAD

**Issue by minouHub** [radis/radis#272]
### 🐛 Describe the bug
This example is not working anymore: https://radis.readthedocs.io/en/master/examples/examples.html

### 🖥 Steps To Reproduce

```python
from radis import SpectrumFactory

benchmark_line_brd_ratio = 50    # “WavenumberWingHW”/HWHMs
dnu = 0.01         # step in HAPI Benchmark article
molecule = 'CO'
wavenum_min = 0.001
wavenum_max = 11505
pressure_bar = 1.01315
T = 296
isotopes = [1, 2, 3, 4]

sf = SpectrumFactory(wavenum_min=wavenum_min,
                     wavenum_max=wavenum_max,
                     isotope=isotopes,  #'all',
                     verbose=2,
                     wstep=dnu,     # depends on HAPI benchmark.
                     cutoff=1e-23,
                     broadening_max_width=5.73,  # Corresponds to WavenumberWingHW/HWHM=50 in HAPI
                     molecule=molecule,
                     optimization=None,
                     )
sf.fetch_databank('astroquery', load_energies=False)

s = sf.eq_spectrum(Tgas=T, pressure=pressure_bar)
s.plot()
```
returns

```python
Traceback (most recent call last):

  File "/home/minou/Python/UCLA_CO/rapid_calc2.py", line 33, in <module>
    s = sf.eq_spectrum(Tgas=T, pressure=pressure_bar)

  File "/home/minou/Python/radis/radis/lbl/factory.py", line 692, in eq_spectrum
    wavenumber, abscoeff_v = self._calc_broadening()

  File "/home/minou/Python/radis/radis/lbl/broadening.py", line 2255, in _calc_broadening
    (wavenumber, abscoeff) = self._broaden_lines(df)

  File "/home/minou/Python/radis/radis/lbl/broadening.py", line 2031, in _broaden_lines
    line_profile = self._calc_lineshape(df)  # usually the bottleneck

  File "/home/minou/Python/radis/radis/lbl/broadening.py", line 1296, in _calc_lineshape
    line_profile = self._voigt_broadening(dg, wbroad_centered, jit=jit)

  File "/home/minou/Python/radis/radis/lbl/broadening.py", line 1211, in _voigt_broadening
    lineshape = voigt_lineshape(wbroad_centered, hwhm_lorentz, hwhm_voigt, jit=jit)

  File "/home/minou/Python/radis/radis/lbl/broadening.py", line 564, in voigt_lineshape
    lineshape = _whiting_jit(w_centered, wl, wv)

TypeError: expected dtype object, got 'numpy.dtype[float64]'

```
### 💡 Possible solutions
Not use the `_whiting_jit` function. By the way, what is the difference with `whiting1968`?

**Comment by erwanp** [comment]
Jit version is compiled ("just in time ") so is much master. 

Thanks for reporting! which version is it? 
```
radis.get_version()
```

**Comment by minouHub** [comment]
```python
radis.get_version()
Out[23]: '0.9.29'
```

**Comment by erwanp** [comment]
So not the development version (it should show a Git number) 

What's your Numba version? Can go try to update it  to >= 0.51.0?  I found a similar error in https://github.com/dask/dask-ml/issues/802

**Comment by minouHub** [comment]
I just pulled on the develop and ran `pip install -e .` and it is still on the 0.9.29

I'm on numba 0.50.1 which is the latest version on conda, see https://numba.pydata.org/numba-doc/latest/release-notes.html. If I try to force it on pip this is what I get (and I don't want to mess with dependence ^^) 

```
minou@minou-VMware:~/Python/radis$ pip install numba==0.51.0
Collecting numba==0.51.0
  Downloading numba-0.51.0-cp37-cp37m-manylinux2014_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 9.7 MB/s 
Collecting llvmlite<0.35,>=0.34.0.dev0
  Downloading llvmlite-0.34.0-cp37-cp37m-manylinux2010_x86_64.whl (24.6 MB)
     |████████████████████████████████| 24.6 MB 16.6 MB/s 
Requirement already satisfied: setuptools in /home/minou/anaconda3/envs/specair/lib/python3.7/site-packages (from numba==0.51.0) (49.1.0.post20200710)
Requirement already satisfied: numpy>=1.15 in /home/minou/anaconda3/envs/specair/lib/python3.7/site-packages (from numba==0.51.0) (1.20.0)
Installing collected packages: llvmlite, numba
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.33.0+1.g022ab0f
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by erwanp** [comment]
Hello @minouHub . Nothing new on this ??

**Comment by minouHub** [comment]
Hi, sorry for the delay. Pulled new version of Radis and the bug example is now working. Did you do something? Anyway, I can close the issue now :)

**Comment by erwanp** [comment]
Nothing new, looks like a dependency problem. Glad it's fixed !
