### ISSUE TITLE
"Numba could not be imported" error when RADIS 0.9.29-master is used

### ISSUE THREAD

**Issue by BlehMaks** [radis/radis#279]
### 🐛 Describe the bug
Dear RADIS team,

After installation of master version of current radis release I met a problem that it is not possible to load Numba package although it is installed of the latest version with all dependencies. (Even `from radis import get_version` gave the error below)

Traceback:
```
>>> from radis import get_version
Traceback (most recent call last):
  File "C:\Users\tj4737\radis_fitting\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module> from numba.core.typeconv import _typeconv
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\tj4737\radis_fitting\radis\radis\__init__.py", line 74, in <module> from .misc.config import get_config
  File "c:\users\tj4737\radis_fitting\radis\radis\misc\__init__.py", line 8, in <module> from .arrays import (
  File "c:\users\tj4737\radis_fitting\radis\radis\misc\arrays.py", line 14, in <module> import numba
  File "C:\Users\tj4737\radis_fitting\lib\site-packages\numba\__init__.py", line 24, in <module> from numba.misc.special import (
  File "C:\Users\tj4737\radis_fitting\lib\site-packages\numba\misc\special.py", line 3, in <module> from numba.core.typing.typeof import typeof
  File "C:\Users\tj4737\radis_fitting\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module> from .context import BaseContext, Context
  File "C:\Users\tj4737\radis_fitting\lib\site-packages\numba\core\typing\context.py", line 11, in <module> from numba.core.typeconv import Conversion, rules
  File "C:\Users\tj4737\radis_fitting\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module> from .typeconv import TypeManager, TypeCastingRules
  File "C:\Users\tj4737\radis_fitting\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module> raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide https://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: The specified module could not be found.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Users\tj4737\radis_fitting\Scripts\python.exe
```

### 💡 Possible solutions
It was recommended by @erwanp to check https://github.com/numba/numba/issues/6973 problem in Numba github.
The solution in the bottom of the issue worked for me: "I have temporarily fixed my issue by pinning dependencies as follows: llvmlite==0.32.1, numba==0.47.0."
Although this is only a temporal solution. 

Best regards,
Maksim

**Comment by erwanp** [comment]
Thanks for posting as it will help others that encounter the same error message to find the solution. 

I'm closing as it's not related to Radis, and should be probably solved starting from an Anaconda installation (@BlehMaks uses virtualenv here). Re-open if needed!
