### ISSUE TITLE
Profiler return error when calculation time is near zero

### ISSUE THREAD

**Issue by minouHub** [radis/radis#305]
### 🐛 Describe the bug
When calculating small spectra, the profiler sometimes perform a division by zero.

### 🖥 Steps To Reproduce
```python
from radis import SpectrumFactory
sf = SpectrumFactory(wavenum_min=2384,
                     wavenum_max=2385,
                     molecule='CO2',
                      isotope='1,2',
                     broadening_max_width=10,  # cm-1
                     medium='vacuum',
                     verbose=3,    # more for more details
                     )
sf.fetch_databank()
s = sf.eq_spectrum(Tgas=300, path_length=1)
```

Returns:
```python
----------------------------------------
Scaling equilibrium linestrength
0.02s - Scaled equilibrium linestrength
0.00s - Calculated lineshift
0.00s - Calculate broadening HWHM
Calculating line broadening (260 lines: expect ~ 0.03s on 1 CPU)
...... 0.00s - Precomputed DLM lineshapes (10)
...... 0.00s - Initialized vectors
...... 0.00s - Get closest matching line & fraction
...... 0.00s - Distribute lines over DLM
...... 0.00s - Convolve and sum on spectral range
0.00s - Calculated line broadening
0.00s - Calculated other spectral quantities
0.03s - Spectrum calculated (before object generation)
0.00s - Generated Spectrum object
0.03s - Spectrum calculated
e:\python\radis\radis\io\cache_files.py:526: UserWarning: Dataframe in C:\Users\mines\.astropy\cache\astroquery\Hitran\tempfile_CO2_1_2379.00_2390.00.h5 contains `object` format columns: ['globu', 'globl', 'locu', 'locl', 'lmix']. Operations will be slower. Try to convert them to numeric.
  warn(
e:\python\radis\radis\io\cache_files.py:526: UserWarning: Dataframe in C:\Users\mines\.astropy\cache\astroquery\Hitran\tempfile_CO2_2_2379.00_2390.00.h5 contains `object` format columns: ['globu', 'globl', 'locu', 'locl', 'lmix']. Operations will be slower. Try to convert them to numeric.
  warn(
e:\python\radis\radis\misc\warning.py:319: MissingSelfBroadeningWarning: Self-broadening temperature coefficient Tdpsel not given in database: used Tdpair instead
  warnings.warn(WarningType(message))
Traceback (most recent call last):

  File "E:\Python\UCLA\0-shock_tube\untitled2.py", line 18, in <module>
    s = sf.eq_spectrum(Tgas=300, path_length=1)

  File "e:\python\radis\radis\lbl\factory.py", line 812, in eq_spectrum
    self.profiler.percentage_distribution()

  File "e:\python\radis\radis\misc\profiler.py", line 110, in percentage_distribution
    verbose_distribution[i][j][0] / total_sum_verbose_wise[i] * 100,

ZeroDivisionError: float division by zero
```

### 💡 Possible solutions
Is it due to some rounding somewhere? Otherwise if the calculation is really really close to zero, why not using a `try`, catch a division and throw 0%?

**Comment by anandxkumar** [comment]
Ok on it :+1:

**Comment by anandxkumar** [comment]
@minouHub I tried the same code on my laptop, it computed the `sf.profiler.relative_time_percentage`  without any issue 

```
{1: [('spectrum_calculation', [100.0, 0.027795076370239258])],
 2: [('spectrum_calc_before_obj', [56.05367759470019, 0.0196688175201416]),
  ('generate_spectrum_obj', [22.632240529981313, 0.007941484451293945]),
  ('scaled_eq_linestrength', [7.7309325632750125, 0.002712726593017578]),
  ('calc_hwhm', [5.83115338882283, 0.0020461082458496094]),
  ('calc_line_broadening', [4.447086801426873, 0.0015604496002197266]),
  ('calc_other_spectral_quan', [1.807372175980975, 0.0006341934204101562]),
  ('calc_lineshift', [1.4975369458128078, 0.0005254745483398438])],
 3: [('precompute_DLM_lineshapes', [42.02925384188113, 0.0005412101745605469]),
  ('DLM_convolve', [36.585817441214594, 0.0004711151123046875]),
  ('DLM_closest_matching_line', [17.7744862062581, 0.0002288818359375]),
  ('DLM_Distribute_lines', [3.1475652656915383, 4.0531158447265625e-05]),
  ('DLM_Initialized_vectors', [0.462877244954638, 5.9604644775390625e-06])]}
```
Maybe when time is very small it might go out of limit of float so we can add  can add try and except.

**Comment by minouHub** [comment]
maybe my computer is too fast :)
