### ISSUE TITLE
Partition function calculation stuck in Spyder with "tabulation" mode (vaex)

### ISSUE THREAD

**Issue by erwanp** [radis/radis#338]
### 🐛 Describe the bug

As already seen in #316 , the just-in-time tabulation of partition functions with `parsum_mode='tabulation'` is stuck if ran within a Spyder iPython console.

### 🖥 Steps To Reproduce

Run the following snippet in a Spyder console : 

```python
import radis
radis.DEBUG_MODE = True
from radis import SpectrumFactory
sf = SpectrumFactory(wmin=2283.7,
                      wmax=2285,
                      isotope='1,2,3',
                      verbose=3,    # more for more details
                      parsum_mode="tabulation"     # 👈 comment to run in normal mode
                      )
sf.load_databank('HITEMP-CO2-TEST')        # predefined in ~/radis.json
s = sf.non_eq_spectrum(Tvib=3000, Trot=2000, path_length=1)
s.print_perf_profile()

```

The stuck happens when computing a mean with vaex.

Even more minimal error : 
```python
import numpy as np
import vaex
df = vaex.from_dict({"E":np.random.rand(1000)})
print(df)
print("before EQ mean")
E_bins = df.mean("E", binby="E", shape=10)
print("after EQ mean")       # 👈 I never get to here
```

Script works well if 
- ran from an Ipython ( 7.22.0) console in the terminal 
- ran from Python in the terminal
- ran from VS Code
- ran from Jupyter Lab (3.0.14)
- ran in Jupyter QtConsole

As pointed out by @minouHub , opening a new Spyder IPython console unlocks the process. If console has been "unlocked", I can even re-run the script another time before it gets stuck again. (?)

Last thing : although no graphics are plot anywhere in this example, this problem appears when my iPython console has **Qt5** output graphics. It does not appear with **Inline** graphics (tried both consistently 3 times)

> spyder                    5.0.5            py38haa95532_2
> spyder-kernels            2.0.5            py38haa95532_0
> ipython                   7.22.0           py38hd4e2768_0

on Windows.

**Comment by erwanp** [comment]
Reported to the Spyder team https://github.com/spyder-ide/spyder/issues/16183

**Comment by BlehMaks** [comment]
Hello,
with enabled `parsum_mode="tabulation"` in plot_multi_temperature_fit.py example my spyder 5.0.3 crashes without explanation and running from terminal gives an error with the following traceback:

```
ERROR:MainThread:vaex.execution:error in task, flush task queue
Traceback (most recent call last):
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\vaex\execution.py", line 219, in execute_async  task._result = parts[0].get_result()
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\vaex\cpu.py", line 532, in get_result
    result = result.copy()
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 206. MiB for an array with shape (300, 300, 300) and data type int64
Traceback (most recent call last):
  File "examples/plot_multi_temperature_fit.py", line 70, in <module>
    s_best, best = sf.fit_spectrum(
  File "c:\users\blekhshtein\radis\radis\lbl\factory.py", line 1860, in fit_spectrum
    return fit_spectrum(
  File "c:\users\blekhshtein\radis\radis\tools\fitting.py", line 217, in fit_spectrum
    compute_los_model(
  File "c:\users\blekhshtein\radis\radis\tools\fitting.py", line 211, in <lambda>
    compute_los_model = lambda fit_parameters: model(
  File "c:\users\blekhshtein\radis\radis\tools\fitting.py", line 131, in Tvib12Tvib3Trot_NonLTEModel
    s = factory.non_eq_spectrum(**kwargs)
  File "c:\users\blekhshtein\radis\radis\lbl\factory.py", line 1328, in non_eq_spectrum
    self._calc_populations_noneq_multiTvib(
  File "c:\users\blekhshtein\radis\radis\lbl\base.py", line 2742, in _calc_populations_noneq_multiTvib
    / Q(Tvib, Trot)
  File "c:\users\blekhshtein\radis\radis\lbl\base.py", line 2655, in Q
    Q_dict[iso] = parsum.at_noneq_3Tvib(
  File "c:\users\blekhshtein\radis\radis\levels\partfunc.py", line 809, in at_noneq_3Tvib
    return self._noneq_3Tvib_tabulation_eval(
  File "c:\users\blekhshtein\radis\radis\levels\partfunc.py", line 962, in _noneq_3Tvib_tabulation_eval
    self._noneq_3Tvib_tabulation_setup(
  File "c:\users\blekhshtein\radis\radis\levels\partfunc.py", line 897, in _noneq_3Tvib_tabulation_setup
    g_bins_neq = df.sum(
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\vaex\dataframe.py", line 943, in sum
    return self._compute_agg('sum', expression, binby, limits, shape, selection, delay, edges, progress, array_type=array_type)
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\vaex\dataframe.py", line 773, in _compute_agg
    return self._delay(delay, var)
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\vaex\dataframe.py", line 1537, in _delay
    self.execute()
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\vaex\dataframe.py", line 375, in execute
    just_run(self.execute_async())
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\vaex\asyncio.py", line 35, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\vaex\dataframe.py", line 380, in execute_async
    await self.executor.execute_async()
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\vaex\execution.py", line 219, in execute_async
    task._result = parts[0].get_result()
  File "C:\Users\Blekhshtein\anaconda3\envs\radis-env\lib\site-packages\vaex\cpu.py", line 532, in get_result
    result = result.copy()
numpy.core._exceptions.MemoryError: Unable to allocate 206. MiB for an array with shape (300, 300, 300) and data type int64
```

**Comment by erwanp** [comment]
The table used to compute the  partition functions is too large for your system. 

You can adjust it by reducing the [N_bins](https://github.com/radis/radis/blob/74c9883d0063060a3bca799a0753eb03b2312b3a/radis/levels/partfunc.py#L228) parameter. 

It can be done at runtime by changing `sf.parsum_calc[molecule][isotope][electronic_state].N_bins` . 

It will cost you a bit of accuracy. Below, it turns out that reducing from the default 300 to 100 has no visible impact on a typical spectrum (adjust with your typical conditions). But this makes the tabulation grid 3^3 = 27 times smaller. Should fix your memory problems. 

: 
```
from radis import SpectrumFactory
sf = SpectrumFactory(
    2284.2,
    2284.6,
    wstep=0.001,  # cm-1
    pressure=20 * 1e-3,  # bar
    db_use_cached=True,
    lvl_use_cached=True,
    cutoff=1e-25,
    isotope="1,2",
    path_length=10,  # cm-1
    mole_fraction=0.1 * 28.97 / 44.07,
    broadening_max_width=1,  # cm-1
    medium="vacuum",
    export_populations=None,  # 'vib',
    parsum_mode="tabulation"
)
sf.load_databank("HITEMP-CO2-TEST")

Tvib = (1600, 1600, 2500)
Trot = 1200

sf.load_databank('HITEMP-CO2-TEST')        # predefined in ~/radis.
s0 = sf.non_eq_spectrum(Tvib, Trot)

# now, adjust number of bins in partitoin functino calculator : 
for iso in sf._get_isotope_list():
    sf.parsum_calc['CO2'][iso]["X"].N_bins = 100    #👈 reduce this further if you want
s = sf.non_eq_spectrum(Tvib, Trot)

from radis import plot_diff
plot_diff(s0, s)
```
![image](https://user-images.githubusercontent.com/16088743/128718729-4d5c5f1c-287e-456a-959f-98792018a0d0.png)

**Comment by BlehMaks** [comment]
Thank you for the information.
I thought it is related to the topic, sorry for misposting

**Comment by erwanp** [comment]
All good, this lead to an improvement. We can coarsen the grid for higher dimensions with no impact on accuracy. Proposed in #339

**Comment by erwanp** [comment]
See https://github.com/spyder-ide/spyder/issues/16183#issuecomment-947664125 for latest developments
