### ISSUE TITLE
Exomol H2O failing on the 0.11.1  ('feather' mode)

### ISSUE THREAD

**Issue by minouHub** [radis/radis#408]
### 🐛 Describe the bug
Hello, 
I cannot compute ExoMol spectra on the 0.11.1. I tried on spyder and on Radis lab. 
Sorry, I cannot spend more time on this. In holidays in an hour.

### 🖥 Steps To Reproduce
```python
from radis import calc_spectrum
import radis 

radis.config['MEMORY_MAPPING_ENGINE'] = 'feather'
s = calc_spectrum(2290, 2300,         # cm-1
                  molecule='H2O',
                  isotope='1',
                  pressure=1.01325,   # bar
                  Tgas=700,           # K
                  mole_fraction=0.1,
                  path_length=1,      # cm
                  databank='exomol',   # or use 'hitemp'
                  verbose=False
                  )
s.plot()    # plot the radiance by default 
```
And I got 
```python
Traceback (most recent call last):

  File "E:\Python\bug_radis\untitled0.py", line 12, in <module>
    s = calc_spectrum(2290, 2300,         # cm-1

  File "e:\python\radis\radis\lbl\calc.py", line 507, in calc_spectrum
    generated_spectrum = _calc_spectrum_one_molecule(

  File "e:\python\radis\radis\lbl\calc.py", line 720, in _calc_spectrum_one_molecule
    sf.fetch_databank(**conditions)

  File "e:\python\radis\radis\lbl\loader.py", line 1275, in fetch_databank
    df, local_path, Z_exomol = fetch_exomol(

  File "e:\python\radis\radis\io\exomol.py", line 362, in fetch_exomol
    mdb = MdbExomol(local_path, [load_wavenum_min, load_wavenum_max], engine=engine)

  File "e:\python\radis\radis\io\exomol.py", line 764, in __init__
    Q=self.QTref,

AttributeError: 'MdbExomol' object has no attribute 'QTref'
```

### 🖥 Steps To Reproduce on Radis-lab
```python
%matplotlib inline
from radis import calc_spectrum
s = calc_spectrum(2290, 2300,         # cm-1
                  molecule='H2O',
                  isotope='1',
                  pressure=1.01325,   # bar
                  Tgas=700,           # K
                  mole_fraction=0.1,
                  path_length=1,      # cm
                  databank='exomol',   # or use 'hitemp'
                  verbose=False
                  )
s.plot()
```

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_291/3219838641.py in <module>
      1 get_ipython().run_line_magic('matplotlib', 'inline')
      2 from radis import calc_spectrum
----> 3 s = calc_spectrum(2290, 2300,         # cm-1
      4                   molecule='H2O',
      5                   isotope='1',

/srv/conda/envs/notebook/lib/python3.8/site-packages/radis/lbl/calc.py in calc_spectrum(wmin, wmax, wunit, Tgas, Tvib, Trot, pressure, molecule, isotope, mole_fraction, path_length, databank, medium, wstep, truncation, neighbour_lines, cutoff, parsum_mode, optimization, broadening_method, overpopulation, name, save_to, use_cached, mode, export_lines, verbose, return_factory, **kwargs)
    505         kwargs_molecule.update(**dict_arguments)
    506 
--> 507         generated_spectrum = _calc_spectrum_one_molecule(
    508             wavenum_min=wavenum_min,
    509             wavenum_max=wavenum_max,

/srv/conda/envs/notebook/lib/python3.8/site-packages/radis/lbl/calc.py in _calc_spectrum_one_molecule(wavenum_min, wavenum_max, Tgas, Tvib, Trot, pressure, overpopulation, molecule, isotope, mole_fraction, path_length, databank, medium, wstep, truncation, neighbour_lines, cutoff, parsum_mode, optimization, broadening_method, name, use_cached, verbose, mode, export_lines, return_factory, **kwargs)
    718         conditions["parse_local_global_quanta"] = (not _equilibrium) or export_lines
    719         # Finally, LOAD :
--> 720         sf.fetch_databank(**conditions)
    721     elif exists(databank):
    722         conditions = {

/srv/conda/envs/notebook/lib/python3.8/site-packages/radis/lbl/loader.py in fetch_databank(self, source, database, parfunc, parfuncfmt, levels, levelsfmt, load_energies, include_neighbouring_lines, parse_local_global_quanta, drop_non_numeric, db_use_cached, lvl_use_cached, memory_mapping_engine, load_columns, parallel)
   1273             }  # partition function tabulators for all isotpes
   1274             for iso in isotope_list:
-> 1275                 df, local_path, Z_exomol = fetch_exomol(
   1276                     molecule,
   1277                     database=database,

/srv/conda/envs/notebook/lib/python3.8/site-packages/radis/io/exomol.py in fetch_exomol(molecule, database, local_databases, databank_name, isotope, load_wavenum_min, load_wavenum_max, columns, cache, verbose, clean_cache_files, return_local_path, return_partition_function, engine)
    360     if load_wavenum_max is None:
    361         load_wavenum_max = np.inf
--> 362     mdb = MdbExomol(local_path, [load_wavenum_min, load_wavenum_max], engine=engine)
    363 
    364     # Attributes of the DataFrame

/srv/conda/envs/notebook/lib/python3.8/site-packages/radis/io/exomol.py in __init__(self, path, nurange, margin, crit, bkgdatm, broadf, engine, verbose)
    745                     if (
    746                         engine == "vaex"
--> 747                         and self.trans_file.with_suffix(".hdf5").exists()
    748                     ):
    749                         # if engine == 'feather' we recompute all the time

AttributeError: 'list' object has no attribute 'with_suffix'
```

**Comment by minouHub** [comment]
Moving this portion before the closest if statement, I then get another error.

```python
self.Tref = 296.0
self.QTref = np.array(self.QT_interp(self.Tref))
```

```python
Traceback (most recent call last):

  File "E:\Python\bug_radis\untitled0.py", line 12, in <module>
    s = calc_spectrum(2290, 2300,         # cm-1

  File "e:\python\radis\radis\lbl\calc.py", line 507, in calc_spectrum
    generated_spectrum = _calc_spectrum_one_molecule(

  File "e:\python\radis\radis\lbl\calc.py", line 720, in _calc_spectrum_one_molecule
    sf.fetch_databank(**conditions)

  File "e:\python\radis\radis\lbl\loader.py", line 1275, in fetch_databank
    df, local_path, Z_exomol = fetch_exomol(

  File "e:\python\radis\radis\io\exomol.py", line 362, in fetch_exomol
    mdb = MdbExomol(local_path, [load_wavenum_min, load_wavenum_max], engine=engine)

  File "e:\python\radis\radis\io\exomol.py", line 770, in __init__
    trans = trans[trans.nu_positive].extract()

  File "C:\Users\mines\anaconda3\lib\site-packages\pandas\core\generic.py", line 5478, in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'extract'
```

**Comment by erwanp** [comment]
Pandas / Vaex problem, I'll fix and add two tests. Thanks for reporting 👍
