### ISSUE TITLE
C2H2 from exomol not converted to HITRAN format

### ISSUE THREAD

**Issue by minouHub** [radis/radis#434]
### 🐛 Describe the bug
Cannot run the  example bellow

### 🖥 Steps To Reproduce
```python

from radis import calc_spectrum, plot_diff
import radis
radis.config['MEMORY_MAPPING_ENGINE'] = 'vaex'

p, T = 1, 300
wmin, wmax = 3337, 3339
s1 = calc_spectrum(wmin, wmax,         # cm-1
                  molecule='C2H2',
                  isotope='1',
                  pressure=p,   # bar
                  Tgas=T,
                  mole_fraction=1,
                  databank='exomol',  # or 'hitemp'
                  name='exomol',
                  path_length=10,
                  cutoff=1e-55,
                  wstep = 1e-3
                  )
s1.plot('absorbance')
```

Error:

```python
Traceback (most recent call last):

  File "E:\Python\H2C2_example.py", line 14, in <module>
    s1 = calc_spectrum(wmin, wmax,         # cm-1

  File "e:\python\radis\radis\lbl\calc.py", line 508, in calc_spectrum
    generated_spectrum = _calc_spectrum_one_molecule(

  File "e:\python\radis\radis\lbl\calc.py", line 721, in _calc_spectrum_one_molecule
    sf.fetch_databank(**conditions)

  File "e:\python\radis\radis\lbl\loader.py", line 1298, in fetch_databank
    df, local_path, Z_exomol = fetch_exomol(

  File "e:\python\radis\radis\io\exomol.py", line 368, in fetch_exomol
    mdb = MdbExomol(local_path, [load_wavenum_min, load_wavenum_max], engine=engine)

  File "e:\python\radis\radis\io\exomol.py", line 525, in __init__
    dic_def = exomolapi.read_def(self.def_file)  # approx. 3 ms

  File "e:\python\radis\radis\io\exomolapi.py", line 57, in read_def
    c = np.array(c, dtype=np.float)
```

### 💡 Possible solutions
The error arises because of this piece of code retrieving the molar mass catches an empty string ''.
```python
c = np.unique(dat["VAL"][i].strip(" ").split(" "))
c = np.array(c, dtype=np.float)
``` 
I replaced it by 
```python
mass_list = dat["VAL"][i].strip(" ").split(" ")
mass_list = [x for x in mass_list if x] #to make sure we remove all empty str (e.g. C2H2)
c = np.unique(mass_list)
``` 
but then another error rises in the vaex conversion 

```python
Traceback (most recent call last):

  File "e:\python\h2c2_example.py", line 14, in <module>
    s1 = calc_spectrum(wmin, wmax,         # cm-1

  File "e:\python\radis\radis\lbl\calc.py", line 508, in calc_spectrum
    generated_spectrum = _calc_spectrum_one_molecule(

  File "e:\python\radis\radis\lbl\calc.py", line 721, in _calc_spectrum_one_molecule
    sf.fetch_databank(**conditions)

  File "e:\python\radis\radis\lbl\loader.py", line 1298, in fetch_databank
    df, local_path, Z_exomol = fetch_exomol(

  File "e:\python\radis\radis\io\exomol.py", line 368, in fetch_exomol
    mdb = MdbExomol(local_path, [load_wavenum_min, load_wavenum_max], engine=engine)

  File "e:\python\radis\radis\io\exomol.py", line 572, in __init__
    states = exomolapi.read_states(self.states_file, dic_def, engine="vaex")

  File "e:\python\radis\radis\io\exomolapi.py", line 218, in read_states
    dat = vaex.read_csv(

  File "C:\Users\mines\anaconda3\lib\site-packages\vaex\__init__.py", line 594, in read_csv
    return from_csv(filepath_or_buffer, **kwargs)

  File "C:\Users\mines\anaconda3\lib\site-packages\vaex\__init__.py", line 567, in from_csv
    vaex.convert.convert_csv(

  File "C:\Users\mines\anaconda3\lib\site-packages\vaex\convert.py", line 52, in convert_csv
    cached_output(*args, **kwargs)

  File "C:\Users\mines\anaconda3\lib\site-packages\vaex\cache.py", line 422, in call
    value = callable(*args, **kwargs)

  File "C:\Users\mines\anaconda3\lib\site-packages\vaex\convert.py", line 51, in cached_output
    _from_csv_convert_and_read(path_input, path_output=path_output, fs_options=fs_options_input, fs=fs_input, progress=progress, **kwargs)

  File "C:\Users\mines\anaconda3\lib\site-packages\vaex\convert.py", line 70, in _from_csv_convert_and_read
    csv_reader = pd.read_csv(filename_or_buffer, chunksize=chunk_size, **kwargs)

  File "C:\Users\mines\anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\mines\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)

  File "C:\Users\mines\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 479, in _read
    _validate_names(kwds.get("names", None))

  File "C:\Users\mines\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 460, in _validate_names
    raise ValueError("Duplicate names are not allowed.")

ValueError: Duplicate names are not allowed.
```
I will try to sort it tonight hopefully but if someone wants to try they are welcome!
EDIT: did not find time

**Comment by minouHub** [comment]
Same with C2H4

**Comment by erwanp** [comment]
Investigating this; I noted that the C2H2 molar mass is wrong in the [ExoMol definition file](https://exomol.com/db/C2H2/12C2-1H2/aCeTY/12C2-1H2__aCeTY.def). It writes 
```
12.0   .1992646880e-25                                                          # Isotopologue mass (Da) and (kg)
```
should be 26.0   Da    and .4317401573e-26 kg

**Comment by erwanp** [comment]
There is a 2nd typo in the definition file : 
```
v5 CHH bending                                                                  # Description quantum label 6
v5                                                                              # Quantum label 6
I3 %3d                                                                          # Format quantum label 6
v5 CHH bending                                                                  # Description quantum label 7
v5                                                                              # Quantum label 7
I3 %3d                                                                          # Format quantum label 7
```
Both are written as "v5", should be "v5" and "v6"

This one is what triggered the Duplicate error @minouHub

**Comment by erwanp** [comment]
(all of the above have been corrected; PR coming)

3rd problem : the C2H2 transition file does not give the transition wavenumber. You're supposed to recompute it from the upper & lower level id (saves space). This is not currently implemented in RADIS
