### ISSUE TITLE
Bug Report: Exomol, hdf5 tests failing on travis (buffer error)

### ISSUE THREAD

**Issue by anandxkumar** [radis/radis#486]
### 🐛 Describe the bug

Travis failing: https://app.travis-ci.com/github/radis/radis/jobs/571532389

Steps to reproduce:
- create a new virtual environment using `conda create -n radis_env python=3.8`  and fetch latest develop branch locally
- `pip install -e .`  (pip install -e .[dev] -v didn't work)
- delete `radis.json` and `.radisdb`
- `pytest`

<details>
  <summary>Following is the version of dependencies in the environment:</summary>

- anyio==3.6.1
- aplus==0.11.0
- argon2-cffi==21.3.0
- argon2-cffi-bindings==21.2.0
- asgiref==3.5.2
- astropy==5.1
- astroquery==0.4.6
- asttokens==2.0.5
- attrs==21.4.0
- backcall==0.2.0
- beautifulsoup4==4.11.1
- blake3==0.3.1
- bleach==5.0.0
- bqplot==0.12.33
- cachetools==5.2.0
- certifi==2022.5.18.1
- cffi==1.15.0
- charset-normalizer==2.0.12
- click==8.1.3
- cloudpickle==2.1.0
- commonmark==0.9.1
- configparser==5.2.0
- cryptography==37.0.2
- cycler==0.11.0
- Cython==0.29.30
- dask==2022.5.2
- debugpy==1.6.0
- decorator==5.1.1
- defusedxml==0.7.1
- entrypoints==0.4
- executing==0.8.3
- fastapi==0.78.0
- fastjsonschema==2.15.3
- filelock==3.7.0
- fonttools==4.33.3
- frozendict==2.3.2
- fsspec==2022.5.0
- future==0.18.2
- h11==0.13.0
- h5py==3.7.0
- habanero==1.2.2
- hitran-api==1.2.2.0
- hjson==3.0.2
- html5lib==1.1
- httptools==0.4.0
- idna==3.3
- importlib-metadata==4.11.4
- importlib-resources==5.7.1
- iniconfig==1.1.1
- ipydatawidgets==4.3.1.post1
- ipykernel==6.13.0
- ipyleaflet==0.16.0
- ipympl==0.9.1
- ipython==8.4.0
- ipython-genutils==0.2.0
- ipyvolume==0.5.2
- ipyvue==1.7.0
- ipyvuetify==1.8.2
- ipywebrtc==0.6.0
- ipywidgets==7.7.0
- jedi==0.18.1
- jeepney==0.8.0
- Jinja2==3.1.2
- joblib==1.1.0
- json-tricks==3.15.5
- jsonschema==4.5.1
- jupyter-client==7.3.1
- jupyter-core==4.10.0
- jupyterlab-pygments==0.2.2
- jupyterlab-widgets==1.1.0
- keyring==23.5.1
- kiwisolver==1.4.2
- llvmlite==0.38.1
- locket==1.0.0
- lxml==4.8.0
- MarkupSafe==2.1.1
- matplotlib==3.5.2
- matplotlib-inline==0.1.3
- mistune==0.8.4
- mpldatacursor==0.7.1
- nbclient==0.6.3
- nbconvert==6.5.0
- nbformat==5.4.0
- nest-asyncio==1.5.5
- notebook==6.4.11
- numba==0.55.2
- numexpr==2.8.1
- numpy==1.22.4
- packaging==21.3
- pandas==1.4.2
- pandocfilters==1.5.0
- parso==0.8.3
- partd==1.2.0
- PeakUtils==1.3.3
- pexpect==4.8.0
- pickleshare==0.7.5
- Pillow==9.1.1
- plotly==5.8.0
- pluggy==1.0.0
- progressbar2==4.0.0
- prometheus-client==0.14.1
- prompt-toolkit==3.0.29
- psutil==5.9.1
- ptyprocess==0.7.0
- publib==0.3.3
- pure-eval==0.2.2
- py==1.11.0
- pyarrow==8.0.0
- pycparser==2.21
- pydantic==1.9.1
- pyerfa==2.0.0.1
- Pygments==2.12.0
- pyparsing==3.0.9
- pyrsistent==0.18.1
- pytest==7.1.2
- python-dateutil==2.8.2
- python-dotenv==0.20.0
- python-utils==3.3.2
- pythreejs==2.3.0
- pytz==2022.1
- pyvo==1.3
- PyYAML==6.0
- pyzmq==23.0.0
- -e git+https://github.com/anandxkumar/radis.git@1136890cc2b84734fe037373a48969b3444ce190#egg=radis
- requests==2.27.1
- rich==12.4.4
- scipy==1.8.1
- seaborn==0.11.2
- SecretStorage==3.3.2
- Send2Trash==1.8.0
- six==1.16.0
- sniffio==1.2.0
- soupsieve==2.3.2.post1
- stack-data==0.2.0
- starlette==0.19.1
- tables==3.7.0
- tabulate==0.8.9
- tenacity==8.0.1
- termcolor==1.1.0
- terminado==0.15.0
- tinycss2==1.1.1
- tomli==2.0.1
- toolz==0.11.2
- tornado==6.1
- tqdm==4.64.0
- traitlets==5.2.1.post0
- traittypes==0.2.1
- tuna==0.5.11
- typing_extensions==4.2.0
- urllib3==1.26.9
- uvicorn==0.17.6
- uvloop==0.16.0
- vaex==4.9.1
- vaex-astro==0.9.1
- vaex-core==4.9.1
- vaex-hdf5==0.12.1
- vaex-jupyter==0.7.0
- vaex-ml==0.17.0
- vaex-server==0.8.1
- vaex-viz==0.5.1
- watchgod==0.8.2
- wcwidth==0.2.5
- webencodings==0.5.1
- websockets==10.3
- widgetsnbextension==3.6.0
- xarray==2022.3.0
- xyzservices==2022.4.0
- zipp==3.8.0

</details>
<details>
<summary> Error </summary>

platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/travis/build/radis/radis, configfile: setup.cfg
plugins: cov-3.0.0, asdf-2.11.1, anyio-3.6.1
collected 227 items / 16 deselected / 211 selected                             
radis/test/test_misc.py ......                                           [  2%]
radis/test/test_phys.py ..                                               [  3%]
radis/test/db/test_molecule_lists.py ..                                  [  4%]
radis/test/db/test_molecules.py ...                                      [  6%]
radis/test/db/test_molparams.py .                                        [  6%]
radis/test/io/test_exomol.py .FF                                         [  8%]
radis/test/io/test_geisa.py ...                                          [  9%]
radis/test/io/test_hdf5.py FF                                            [ 10%]
radis/test/io/test_hitemp.py Warning : 1 files were written but not combined. Deleting them.
['/home/travis/.radisdb/hitemp/OH-13_HITEMP2020_temp00000.hdf5']
F..Warning : 1 files were written but not combined. Deleting them.
['/home/travis/.radisdb/hitemp/OH-13_HITEMP2020_temp00000.hdf5']
Exception ignored in: <function DataFileManager.__del__ at 0x7fcecc2eec10>
Traceback (most recent call last):
  File "/home/travis/build/radis/radis/radis/api/hdf5.py", line 238, in __del__
    self._close_temp_batch_files()
  File "/home/travis/build/radis/radis/radis/api/hdf5.py", line 225, in _close_temp_batch_files
    os.remove(self._temp_batch_files[i])
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/.radisdb/hitemp/OH-13_HITEMP2020_temp00000.hdf5'
FFWarning : 1 files were written but not combined. Deleting them.
['/home/travis/.radisdb/hitemp/CO2-02_02500-03000_HITEMP2010_temp00000.hdf5']
FFF                                    [ 14%]
radis/test/io/test_hitran_cdsd.py .......                                [ 17%]
radis/test/io/test_query.py ....Warning : 1 files were written but not combined. Deleting them.
['/home/travis/.radisdb/hitemp/CO-05_HITEMP2019_temp00000.hdf5']
FWarning : 1 files were written but not combined. Deleting them.
['/home/travis/build/radis/radis/radis/test/files/hitran/CO_temp00000.hdf5']
FWarning : 1 files were written but not combined. Deleting them.
['/home/travis/.radisdb/hitran/CO_temp00000.hdf5']
F                                      [ 20%]
radis/test/lbl/test_bands.py .                                           [ 21%]
radis/test/lbl/test_base.py .......F                                     [ 25%]
radis/test/lbl/test_broadening.py ........FF                             [ 29%]
radis/test/lbl/test_calc.py .FF.FWarning : 1 files were written but not combined. Deleting them.
['/home/travis/.radisdb/hitran/CO2_temp00000.hdf5']
FWarning : 1 files were written but not combined. Deleting them.
['/home/travis/.radisdb/hitran/CO_temp00000.hdf5']
F.F.                                   [ 34%]
radis/test/lbl/test_database.py ..                                       [ 35%]
radis/test/lbl/test_factory.py ................                          [ 43%]
radis/test/lbl/test_labels.py .                                          [ 43%]
radis/test/lbl/test_loader.py ....                                       [ 45%]
radis/test/lbl/test_overp.py .                                           [ 45%]
radis/test/lbl/test_spectrum.py ....                                     [ 47%]
radis/test/levels/test_partfunc.py .............                         [ 54%]
radis/test/los/test_slabs.py ....                                        [ 55%]
radis/test/misc/test_arrays.py .............                             [ 62%]
radis/test/misc/test_basics.py ...                                       [ 63%]
radis/test/misc/test_config.py ..                                        [ 64%]
radis/test/misc/test_utils.py ..                                         [ 65%]
radis/test/phys/test_blackbody.py ...                                    [ 66%]
radis/test/phys/test_dunham.py ..                                        [ 67%]
radis/test/phys/test_units.py .                                          [ 68%]
radis/test/spectrum/test_compare.py .FF                                  [ 69%]
radis/test/spectrum/test_operations.py ............                      [ 75%]
radis/test/spectrum/test_rescale.py ........                             [ 79%]
radis/test/spectrum/test_spectrum.py ...............                     [ 86%]
radis/test/spectrum/test_utils.py ..                                     [ 87%]
radis/test/tools/test_database.py ....F                                  [ 89%]
radis/test/tools/test_gascomp.py .                                       [ 90%]
radis/test/tools/test_line_survey.py ..                                  [ 90%]
radis/test/tools/test_slit.py ...........                                [ 96%]
radis/test/tools/test_track_ref.py .FWarning : 1 files were written but not combined. Deleting them.
['/home/travis/.radisdb/hitran/CO_temp00000.hdf5']
FWarning : 1 files were written but not combined. Deleting them.
['/home/travis/.radisdb/hitran/CO_temp00000.hdf5']
FF                                 [ 98%]
radis/test/validation/test_CO2_3Tvib_vs_klarenaar.py .                   [ 99%]
radis/test/validation/test_RADIS_vs_HAPI_line_broadening.py F            [ 99%]
radis/test/validation/test_validation_vs_specair_noneqCO.py .            [100%]Warning : 1 files were written but not combined. Deleting them.
['/home/travis/.radisdb/hitran/CO2_temp00000.hdf5']
=================================== FAILURES ===================================
__________________________ test_calc_exomol_spectrum ___________________________
verbose = True, plot = True, args = (), kwargs = {}
calc_spectrum = <function calc_spectrum at 0x7fcec4b66b80>
    @pytest.mark.needs_connection
    def test_calc_exomol_spectrum(verbose=True, plot=True, *args, **kwargs):
        """Auto-fetch and calculate a SiO spectrum from the ExoMol database
    
        https://github.com/radis/radis/pull/320#issuecomment-884508206
        """
        from radis import calc_spectrum
    
>       s = calc_spectrum(
            1080,
            1320,  # cm-1
            molecule="SiO",
            isotope="1",
            pressure=1.01325,  # bar
            Tgas=1000,  # K
            mole_fraction=0.1,
            path_length=1,  # cm
            broadening_method="fft",  # @ dev: Doesn't work with 'voigt'
            databank=("exomol", "EBJT"),
            verbose=verbose,
        )
radis/test/io/test_exomol.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
radis/lbl/calc.py:514: in calc_spectrum
    generated_spectrum = _calc_spectrum_one_molecule(
radis/lbl/calc.py:753: in _calc_spectrum_one_molecule
    sf.fetch_databank(**conditions)
radis/lbl/loader.py:1302: in fetch_databank
    df, local_path, Z_exomol = fetch_exomol(
radis/io/exomol.py:202: in fetch_exomol
    mdb = MdbExomol(
radis/api/exomolapi.py:1104: in __init__
    mgr.write(mgr.cache_file(self.states_file), states)
radis/api/hdf5.py:192: in write
    df.export_hdf5(file, group=key, mode="w")
../../../micromamba/envs/radis-env/lib/python3.8/site-packages/vaex/dataframe.py:6912: in export_hdf5
    writer.write(
../../../micromamba/envs/radis-env/lib/python3.8/site-packages/vaex/hdf5/writer.py:42: in __exit__
    self.close()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <vaex.hdf5.writer.Writer object at 0x7fcec09fcc40>
    def close(self):
        if self.mmap is not None:
>           self.mmap.close()
E           BufferError: cannot close exported pointers exist
../../../micromamba/envs/radis-env/lib/python3.8/site-packages/vaex/hdf5/writer.py:34: BufferError
----------------------------- Captured stdout call -----------------------------
Background atmosphere:  Air
Downloading http://www.exomol.com/db/SiO/28Si-16O/EBJT/28Si-16O__EBJT.def
Downloading http://www.exomol.com/db/SiO/28Si-16O/EBJT/28Si-16O__EBJT.pf
Downloading http://www.exomol.com/db/SiO/28Si-16O/EBJT/28Si-16O__EBJT.states.bz2
Downloading http://www.exomol.com/db/SiO/28Si-16O/28Si-16O__H2.broad
Error: Couldn't download .broad file at http://www.exomol.com/db/SiO/28Si-16O/28Si-16O__H2.broad and save.
Downloading http://www.exomol.com/db/SiO/28Si-16O/28Si-16O__He.broad
Error: Couldn't download .broad file at http://www.exomol.com/db/SiO/28Si-16O/28Si-16O__He.broad and save.
Downloading http://www.exomol.com/db/SiO/28Si-16O/28Si-16O__air.broad
Error: Couldn't download .broad file at http://www.exomol.com/db/SiO/28Si-16O/28Si-16O__air.broad and save.
Note: Caching states data to the vaex format. After the second time, it will become much faster.

</details>

### 💡 Possible solutions

Error is possibly occurring when fetching data from hitran, hitemp, and merging the temporary data files causing buffer issues. The issue might lie in the `hdf5.py` file which is responsible for downloading and merging the data lines.

Also, a thing to note is that the issue is not reproducible on `radis-lab` so it may be a dependency version specific issue, some compatibility issue between vaex or other packages.

### 🎲 Radis version

'0.13.0'

### 💻 Operating system

Linux

**Comment by anandxkumar** [comment]
Yes! 
The `radis/radis/test/files/hitemp and hitran` gets updated upon pytest which didn't occur earlier.
Also, I had a python=3.6 environment for radis, and pytest is passing for the same. 

Only 1 test in `test_query` failed
<details>
<summary>Error </summary>

radis/test/io/test_query.py:113: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
radis/io/hitran.py:1424: in fetch_hitran
    ldb.register()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <radis.io.hitran.HITRANDatabaseManager object at 0x7f43cc0c7208>

    def register(self):
        """register in ~/radis.json"""
    
        from radis.db import MOLECULES_LIST_NONEQUILIBRIUM
    
        local_files = self.get_filenames()
    
        if self.wmin is None or self.wmax is None:
            print(
                "Somehow wmin and wmax was not given for this database. Reading from the files"
            )
            ##  fix:
            # (can happen if database was downloaded & parsed, but registration failed a first time)
            df_full = self.load(
                local_files,
                columns=["wav"],
                isotope=None,
                load_wavenum_min=None,
>               load_wavenum_max=None,
            )
E           TypeError: load() got an unexpected keyword argument 'isotope'

radis/io/hitran.py:1252: TypeError

</details>
<details>

<summary>Dependencies version</summary>

absl-py==1.0.0
alabaster==0.7.12
aplus==0.11.0
appdirs==1.4.4
argh==0.26.2
argon2-cffi==21.1.0
arrow==0.13.1
asdf==2.8.3
asdf-astropy==0.1.0
asdf-transform-schemas==0.2.0
asdf-wcs-schemas==0.1.1
asgiref==3.4.1
astroid @ file:///tmp/build/80754af9/astroid_1628055155277/work
astropy==4.1
astroquery==0.4.3
async-generator==1.10
atomicwrites==1.4.0
attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1615918855173/work
Babel @ file:///tmp/build/80754af9/babel_1620871417480/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
backports.entry-points-selectable==1.1.0
beautifulsoup4==4.10.0
binaryornot @ file:///tmp/build/80754af9/binaryornot_1617751525010/work
black==21.9b0
blake3==0.2.0
bleach==4.1.0
bokeh==2.3.3
bqplot==0.12.31
brotlipy==0.7.0
bs4==0.0.1
cached-property==1.5.2
cachetools==4.2.4
certifi==2021.5.30
cffi @ file:///tmp/build/80754af9/cffi_1625814693874/work
cfgv==3.3.1
chardet @ file:///tmp/build/80754af9/chardet_1607706739153/work
charset-normalizer==2.0.6
click @ file:///tmp/build/80754af9/click_1621604852318/work
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1632508026186/work
commonmark==0.9.1
configparser==5.0.2
contextvars==2.4
cookiecutter @ file:///tmp/build/80754af9/cookiecutter_1617748928239/work
cryptography==35.0.0
cssselect==1.1.0
cycler==0.10.0
Cython==0.29.24
dask==2021.3.0
dataclasses==0.8
decorator @ file:///tmp/build/80754af9/decorator_1632776554403/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
diff-match-patch @ file:///Users/ktietz/demo/mc3/conda-bld/diff-match-patch_1630511840874/work
distlib==0.3.3
distributed==2021.3.0
docutils @ file:///tmp/build/80754af9/docutils_1620827982266/work
entrypoints==0.3
fake-useragent==0.1.11
fastapi==0.68.2
filelock==3.3.0
flake8 @ file:///tmp/build/80754af9/flake8_1620776156532/work
frozendict==2.0.6
fsspec==2021.10.1
future==0.18.2
gwcs==0.18.0
h11==0.12.0
h5py==3.1.0
habanero==0.7.4
HeapDict==1.0.1
hitran-api==1.2.2.0
hjson==3.0.2
html5lib==1.1
httptools==0.2.0
identify==2.3.0
idna @ file:///tmp/build/80754af9/idna_1622654382723/work
imagesize @ file:///Users/ktietz/demo/mc3/conda-bld/imagesize_1628863108022/work
immutables==0.16
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1631916693255/work
importlib-resources==5.2.2
inflection==0.5.1
iniconfig==1.1.1
intervaltree @ file:///Users/ktietz/demo/mc3/conda-bld/intervaltree_1630511889664/work
ipydatawidgets==4.2.0
ipykernel==5.5.5
ipyleaflet==0.14.0
ipympl==0.8.0
ipython @ file:///tmp/build/80754af9/ipython_1593447367857/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipyvolume==0.5.2
ipyvue==1.6.0
ipyvuetify==1.8.1
ipywebrtc==0.6.0
ipywidgets==7.6.5
isort @ file:///tmp/build/80754af9/isort_1628603791788/work
jedi==0.18.0
jeepney @ file:///tmp/build/80754af9/jeepney_1627537048313/work
Jinja2==3.0.2
jinja2-time @ file:///tmp/build/80754af9/jinja2-time_1617751524098/work
jmespath==0.10.0
joblib==1.0.1
json-tricks==3.15.5
jsonschema @ file:///Users/ktietz/demo/mc3/conda-bld/jsonschema_1630511932244/work
jupyter-client==7.0.6
jupyter-core==4.8.1
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-widgets==1.0.2
k-means-constrained==0.5.2
keyring==23.2.1
kiwisolver==1.3.1
lazy-object-proxy @ file:///tmp/build/80754af9/lazy-object-proxy_1616526919073/work
llvmlite==0.36.0
locket==0.2.1
lxml==4.6.3
MarkupSafe==2.0.1
matplotlib==3.3.4
mccabe==0.6.1
mimeparse==0.1.3
mistune==0.8.4
MouseInfo==0.1.3
mpldatacursor==0.7.1
msgpack==1.0.2
mypy-extensions==0.4.3
nbclient==0.5.4
nbconvert @ file:///tmp/build/80754af9/nbconvert_1601914804165/work
nbformat @ file:///tmp/build/80754af9/nbformat_1617383369282/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
nodeenv==1.6.0
notebook==6.4.4
numba==0.53.1
numexpr==2.7.3
numpy==1.19.5
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
opencv-contrib-python==4.5.5.62
ortools==9.3.10497
packaging @ file:///tmp/build/80754af9/packaging_1625611678980/work
pandas==1.1.5
pandocfilters==1.5.0
parse==1.19.0
parso==0.8.2
partd==1.2.0
pathspec==0.9.0
PeakUtils==1.3.3
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==8.3.2
platformdirs==2.4.0
plotly==5.3.1
pluggy==1.0.0
plumbum==1.7.2
poyo @ file:///tmp/build/80754af9/poyo_1617751526755/work
pre-commit==2.15.0
progressbar2==3.53.3
prometheus-client==0.11.0
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1633440160888/work
protobuf==3.19.4
psutil @ file:///tmp/build/80754af9/psutil_1612297621795/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
publib==0.3.3
py==1.10.0
pyarrow==5.0.0
PyAutoGUI==0.9.53
pycodestyle @ file:///tmp/build/80754af9/pycodestyle_1615748559966/work
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pydantic==1.8.2
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1621600989141/work
pyee==8.2.2
pyflakes @ file:///tmp/build/80754af9/pyflakes_1617200973297/work
PyGetWindow==0.0.9
Pygments @ file:///tmp/build/80754af9/pygments_1629234116488/work
pylint @ file:///tmp/build/80754af9/pylint_1627536508692/work
pyls-spyder==0.4.0
PyMsgBox==1.0.9
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing @ file:///home/linux1/recipes/ci/pyparsing_1610983426697/work
pyperclip==1.8.2
pyppeteer==0.2.6
pyquery==1.4.3
PyRect==0.1.4
pyrsistent==0.18.0
PyScreeze==0.1.28
PySocks @ file:///tmp/build/80754af9/pysocks_1605305763431/work
pytest==6.2.5
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-dotenv==0.19.0
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1600278539111/work
python-lsp-black @ file:///tmp/build/80754af9/python-lsp-black_1634232156041/work
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.2.4
python-slugify @ file:///tmp/build/80754af9/python-slugify_1620405669636/work
python-utils==2.5.6
python-xlib==0.31
python3-xlib==0.15
pythreejs==2.3.0
pytweening==1.0.4
pytz==2021.3
pyvo==1.1
pyxdg @ file:///tmp/build/80754af9/pyxdg_1603822279816/work
PyYAML==5.4.1
pyzmq==22.3.0
QDarkStyle @ file:///tmp/build/80754af9/qdarkstyle_1617386714626/work
qstylizer @ file:///tmp/build/80754af9/qstylizer_1617713584600/work/dist/qstylizer-0.1.10-py2.py3-none-any.whl
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1615991616277/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1632739723211/work
QtPy @ file:///tmp/build/80754af9/qtpy_1629397026935/work
-e git+https://github.com/anandxkumar/radis.git@1136890cc2b84734fe037373a48969b3444ce190#egg=radis
regex==2021.9.30
requests @ file:///tmp/build/80754af9/requests_1629994808627/work
requests-html==0.10.0
rich==12.0.0
rope @ file:///tmp/build/80754af9/rope_1623703006312/work
rpyc==5.0.1
Rtree @ file:///tmp/build/80754af9/rtree_1618420379819/work
scikit-learn==0.24.2
scipy==1.5.4
seaborn==0.11.2
SecretStorage @ file:///tmp/build/80754af9/secretstorage_1614022884787/work
semantic-version==2.9.0
Send2Trash==1.8.0
simplestRPC==1.4.13
six @ file:///tmp/build/80754af9/six_1623709665295/work
sklearn==0.0
snowballstemmer @ file:///tmp/build/80754af9/snowballstemmer_1611258885636/work
sortedcontainers @ file:///tmp/build/80754af9/sortedcontainers_1623949099177/work
soupsieve==2.2.1
specutils==1.3.1
Sphinx @ file:///tmp/build/80754af9/sphinx_1632506123190/work
sphinxcontrib-applehelp @ file:///home/ktietz/src/ci/sphinxcontrib-applehelp_1611920841464/work
sphinxcontrib-devhelp @ file:///home/ktietz/src/ci/sphinxcontrib-devhelp_1611920923094/work
sphinxcontrib-htmlhelp @ file:///tmp/build/80754af9/sphinxcontrib-htmlhelp_1623945626792/work
sphinxcontrib-jsmath @ file:///home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/work
sphinxcontrib-qthelp @ file:///home/ktietz/src/ci/sphinxcontrib-qthelp_1611921055322/work
sphinxcontrib-serializinghtml @ file:///tmp/build/80754af9/sphinxcontrib-serializinghtml_1624451540180/work
spyder @ file:///home/conda/feedstock_root/build_artifacts/spyder_1631797899126/work
spyder-kernels @ file:///home/conda/feedstock_root/build_artifacts/spyder-kernels_1633270854915/work
starlette==0.14.2
tables==3.6.1
tabulate==0.8.9
tblib==1.7.0
tenacity==8.0.1
termcolor==1.1.0
terminado==0.12.1
terminal==0.4.0
testpath @ file:///tmp/build/80754af9/testpath_1624638946665/work
text-unidecode @ file:///Users/ktietz/demo/mc3/conda-bld/text-unidecode_1629401354553/work
textdistance @ file:///tmp/build/80754af9/textdistance_1612461398012/work
threadpoolctl==3.1.0
three-merge @ file:///tmp/build/80754af9/three-merge_1607553261110/work
tinycss @ file:///tmp/build/80754af9/tinycss_1617713798712/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tomli==1.2.1
toolz==0.11.1
tornado @ file:///tmp/build/80754af9/tornado_1606942266872/work
tqdm==4.62.3
traitlets @ file:///tmp/build/80754af9/traitlets_1632746497744/work
traittypes==0.2.1
tuna==0.5.8
typed-ast @ file:///tmp/build/80754af9/typed-ast_1624953671446/work
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1631814937681/work
ujson @ file:///tmp/build/80754af9/ujson_1611259495878/work
Unidecode @ file:///tmp/build/80754af9/unidecode_1614712377438/work
urllib3==1.26.7
uvicorn==0.15.0
uvloop==0.14.0
vaex==4.8.0
vaex-astro==0.9.0
vaex-core==4.8.0
vaex-hdf5==0.12.0
vaex-jupyter==0.7.0
vaex-ml==0.17.0
vaex-server==0.8.1
vaex-viz==0.5.1
varenv==1.0.7
virtualenv==20.8.1
w3lib==1.22.0
watchdog @ file:///tmp/build/80754af9/watchdog_1624955002849/work
watchgod==0.7
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
websockets==9.1
whichcraft @ file:///tmp/build/80754af9/whichcraft_1617751293875/work
widgetsnbextension==3.5.1
wrapt==1.12.1
wurlitzer @ file:///tmp/build/80754af9/wurlitzer_1626947800350/work
xarray==0.16.2
xexplorer @ git+https://github.com/spark-cleantech/xexplorer.git@059616c9dc667b1702d7abe77c32da51e7864f60
yapf @ file:///tmp/build/80754af9/yapf_1615749224965/work
zict==2.0.0
zipp==3.6.0

</details>

This indicates that the issue is definitely due to some package's version incompatibility, which can be the ones used in `hdf5.py`, `hitran.py` or `hitemp.py`, like `astroquery` or `vaex` (`update_pytables_to_vaex` to be specific)

**Comment by anandxkumar** [comment]
Sure! I will give it a try and let you know.
