### ISSUE TITLE
Using store() function with compression being false

### ISSUE THREAD

**Issue by vanfossen** [radis/radis#493]
### 🐛 Describe the bug

I am currently using the `calc_spectrum` and `sPlanck` functions. I want to see the uncompressed JSON that is created from an uncompressed `store()`. I receive an error when `compress=False`. The `.spec` file is created, but is blank.

My environment is WSL 2 for Windows 10. So not necessarily Linux but not necessarily Windows. I also attempted on Radis Lab and the same error occurs, making me feel this is not a WSL exclusive issue. I left in the `savetxt` uncommented because that does successfully return a working `.csv` file.

My `calc_spectrum` code:
```
# ideal transmittance (matches Radis App)
from radis import calc_spectrum
s = calc_spectrum(1900,           # wmin (minimum wavelength/wavenumber) 400
                  2300,           # wmax (maximum wavelength/wavenumber) 12500
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=0.0001,  # Bar
                  Tgas=294.15,      # K
                  Tvib=None,        # vibrational temperature (K)
                  Trot=None,        # rotational temperature (K)
                  mole_fraction=1,
                  path_length=10,   # cm
                  databank='hitran',
                  wstep='auto',
                  use_cached=True,
                  export_lines=False,
                  )
s.apply_slit(0.5, 'nm')
s.store('radis-match.spec', compress=True, if_exists_then='replace')
# s.savetxt('calc_spectrum-1900-2300.csv', 'transmittance_noslit', wunit='cm-1')
```
`calc_spectrum` error:
```
HAPI version: 1.2.2.0
To get the most up-to-date version please check http://hitran.org/hapi
ATTENTION: Python versions of partition sums from TIPS-2021 are now available in HAPI code

           MIT license: Copyright 2021 HITRAN team, see more at http://hitran.org. 

           If you use HAPI in your research or software development,
           please cite it using the following reference:
           R.V. Kochanov, I.E. Gordon, L.S. Rothman, P. Wcislo, C. Hill, J.S. Wilzewski,
           HITRAN Application Programming Interface (HAPI): A comprehensive approach
           to working with spectroscopic data, J. Quant. Spectrosc. Radiat. Transfer 177, 15-30 (2016)
           DOI: 10.1016/j.jqsrt.2016.03.005

           ATTENTION: This is the core version of the HITRAN Application Programming Interface.
                      For more efficient implementation of the absorption coefficient routine, 
                      as well as for new profiles, parameters and other functional,
                      please consider using HAPI2 extension library.
                      HAPI2 package is available at http://github.com/hitranonline/hapi2

Calculating Equilibrium Spectrum
Physical Conditions
----------------------------------------
   Tgas                 294.15 K
   Trot                 294.15 K
   Tvib                 294.15 K
   isotope              1,2,3
   mole_fraction        1
   molecule             CO
   overpopulation       None
   path_length          10 cm
   pressure_mbar        0.1 mbar
   rot_distribution     boltzmann
   self_absorption      True
   state                X
   vib_distribution     boltzmann
   wavenum_max          2300.0000 cm-1
   wavenum_min          1900.0000 cm-1
Computation Parameters
----------------------------------------
   Tref                 296 K
   add_at_used          
   broadening_method    voigt
   cutoff               1e-27 cm-1/(#.cm-2)
   dbformat             hitran
   dbpath               /home/vanfossen/.radisdb/hitran/CO.hdf5
   folding_thresh       1e-06
   include_neighbouring_lines  True
   memory_mapping_engine  auto
   neighbour_lines      0 cm-1
   optimization         simple
   parfuncfmt           hapi
   parsum_mode          full summation
   pseudo_continuum_threshold  0
   sparse_ldm           auto
   truncation           50 cm-1
   waveunit             cm-1
   wstep                auto cm-1
   zero_padding         -1
----------------------------------------
0.89s - Spectrum calculated
/home/vanfossen/.local/lib/python3.8/site-packages/json_tricks/encoders.py:367: UserWarning: json-tricks: numpy scalar serialization is experimental and may work differently in future versions
  warnings.warn('json-tricks: numpy scalar serialization is experimental and may work differently in future versions')
Traceback (most recent call last):
  File "radis_calc.py", line 19, in <module>
    s.store('radis-match.spec', compress=False, if_exists_then='replace')
  File "/home/vanfossen/.local/lib/python3.8/site-packages/radis/spectrum/spectrum.py", line 3301, in store
    return save(
  File "/home/vanfossen/.local/lib/python3.8/site-packages/radis/tools/database.py", line 223, in save
    json_tricks.dump(sjson, f, indent=4)  # takes more space but more readable
  File "/home/vanfossen/.local/lib/python3.8/site-packages/json_tricks/nonp.py", line 134, in dump
    txt = dumps(obj, sort_keys=sort_keys, cls=cls, obj_encoders=obj_encoders, extra_obj_encoders=extra_obj_encoders,
  File "/home/vanfossen/.local/lib/python3.8/site-packages/json_tricks/nonp.py", line 106, in dumps
    txt = cls(sort_keys=sort_keys, obj_encoders=encoders, allow_nan=allow_nan,
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 439, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 316, in _iterencode_list
    yield buf + _floatstr(value)
  File "/usr/lib/python3.8/json/encoder.py", line 239, in floatstr
    raise ValueError(
ValueError: Out of range float values are not JSON compliant: nan
```

My `sPlanck` code:
```
# blackbody spectrum for Tungsten
from radis import sPlanck
s = sPlanck(wavenum_min=1900,  # 400
        wavenum_max=2300,  # 12500
        T=1700,            # blackbody temperature (K) - Globar
        eps=1,             # grey-body emissivity
        medium='air')
s.store('tungsten-small.spec', compress=False, if_exists_then='replace')
# s.savetxt('tungsten-1900-2300.csv', "radiance_noslit")
```
`sPlanck` error:
```
File exists and will be replaced: tungsten-small.spec
Traceback (most recent call last):
  File "radis_calc.py", line 28, in <module>
    s.store('tungsten-small.spec', compress=False, if_exists_then='replace')
  File "/home/vanfossen/.local/lib/python3.8/site-packages/radis/spectrum/spectrum.py", line 3301, in store
    return save(
  File "/home/vanfossen/.local/lib/python3.8/site-packages/radis/tools/database.py", line 223, in save
    json_tricks.dump(sjson, f, indent=4)  # takes more space but more readable
  File "/home/vanfossen/.local/lib/python3.8/site-packages/json_tricks/nonp.py", line 134, in dump
    txt = dumps(obj, sort_keys=sort_keys, cls=cls, obj_encoders=obj_encoders, extra_obj_encoders=extra_obj_encoders,
  File "/home/vanfossen/.local/lib/python3.8/site-packages/json_tricks/nonp.py", line 106, in dumps
    txt = cls(sort_keys=sort_keys, obj_encoders=encoders, allow_nan=allow_nan,
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 439, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 316, in _iterencode_list
    yield buf + _floatstr(value)
  File "/usr/lib/python3.8/json/encoder.py", line 239, in floatstr
    raise ValueError(
ValueError: Out of range float values are not JSON compliant: inf
```

### 🎲 Radis version

0.13.0

### 💻 Operating system

Linux

**Comment by TranHuuNhatHuy** [comment]
@erwanp Yes sir, will take a look at this!

**Comment by erwanp** [comment]
Hello @TranHuuNhatHuy , did you make any progress ?

**Comment by TranHuuNhatHuy** [comment]
Hello Mr. @erwanp , my apologies for forgetting this issue for quite a long time.

After investigating the error log, I assume that the error might be as a result of NaN values in the array (cuz the last time I tried, we couldn't slap NaN into JSON). This script further confirms my theory.

```python
# ideal transmittance (matches Radis App)
from radis import calc_spectrum, experimental_spectrum
import numpy as np
s = calc_spectrum(1900,           # wmin (minimum wavelength/wavenumber) 400
                  2300,           # wmax (maximum wavelength/wavenumber) 12500
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=0.0001,  # Bar
                  Tgas=294.15,      # K
                  Tvib=None,        # vibrational temperature (K)
                  Trot=None,        # rotational temperature (K)
                  mole_fraction=1,
                  path_length=10,   # cm
                  databank='hitran',
                  wstep='auto',
                  use_cached=True,
                  export_lines=False,
                  )
s.apply_slit(0.5, 'nm')

# Pick up a variable, i.e. 'radiance'
w, I = s.get('radiance')

# Purge NaN pairs
s_data_mtr = np.vstack((w, I))
s_data_mtr = s_data_mtr[:, ~np.isnan(s_data_mtr).any(axis = 0)]

# Check if no NaNs left
count = 0
for i in s_data_mtr[1]:
    if np.isnan(i):
        count += 1
assert count == 0

# Recreate the spectrum object with 'radiance' var
s_rad = experimental_spectrum(s_data_mtr[0], s_data_mtr[1])

# Store that 'radiance' variable
s_rad.store('radis-match.spec', compress=False, if_exists_then='replace')
```

If you deem this is the correct reason behind this issue, I shall proceed with dealing with the NaNs.

**Comment by erwanp** [comment]
Good catch

Btw, there is a method trim() or trim_nans() to remove nans on the side of a Spectrum.

Anyway, storing spectra with nans should be a supported feature. Under the hood were using json_tricks and it seems is has an allow_nan=True option. https://github.com/mverleg/pyjson_tricks/blob/799b76ae625900f0add1dbfe8c2642575d9d32ef/README.rst#other-features
Can you try to implement it?

**Comment by anandxkumar** [comment]
@TranHuuNhatHuy would you have time to look into this issue, I'm currently pushing it to milestone 0.15

**Comment by minouHub** [comment]
Pushing this to 0.17
There is no more error when I'm running the example code. @TranHuuNhatHuy can you do a quick check so I can close the issue?

**Comment by minouHub** [comment]
No more error. Closing
