### ISSUE TITLE
Bug Report: Unable to download GEISA molecules

### ISSUE THREAD

**Issue by suzil** [radis/radis#497]
### 🐛 Describe the bug

I'm running this script:
```py
from radis.io.geisa import fetch_geisa

# More molecules will be confirmed and added in upcoming updates
GEISA_working_molecules = [
    'C2H2',
    'C2H4',
    'C2H6',
    'CH4',
    'CO',
    'CO2',
    'H2O',
    'O3',
    'N2O',
    'NO',
    'NO2'
]

for molecule in GEISA_working_molecules:
    fetch_geisa(molecule)
```

And I get the error:

```
$ python download_geisa.py 
Molecule: C2H2
Downloading line_GEISA2020_asc_gs08_v1.0_c2h2 for C2H2 (1/1).
Traceback (most recent call last):
  File "/Users/suzil/Documents/playground/radis-app/server/.venv/lib/python3.9/site-packages/radis/io/dbmanager.py", line 360, in download_and_parse_one_file
    self.ds.open(urlname)
  File "/Users/suzil/Documents/playground/radis-app/server/.venv/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: https://aeris-geisa.ipsl.fr/geisa_files/2020/Lines/line_GEISA2020_asc_gs08_v1.0_c2h2 not found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/suzil/Documents/playground/radis-app/server/download_geisa.py", line 25, in <module>
    fetch_geisa(molecule)
  File "/Users/suzil/Documents/playground/radis-app/server/.venv/lib/python3.9/site-packages/radis/io/geisa.py", line 588, in fetch_geisa
    ldb.download_and_parse(download_urls, download_files)
  File "/Users/suzil/Documents/playground/radis-app/server/.venv/lib/python3.9/site-packages/radis/io/dbmanager.py", line 402, in download_and_parse
    download_and_parse_one_file(urlname, local_file, Ndownload)
  File "/Users/suzil/Documents/playground/radis-app/server/.venv/lib/python3.9/site-packages/radis/io/dbmanager.py", line 362, in download_and_parse_one_file
    raise OSError(
OSError: Problem opening : None. See above. You may want to delete the downloaded file.
```

The issue is a little strange because there is definitely a file at the URL https://aeris-geisa.ipsl.fr/geisa_files/2020/Lines/line_GEISA2020_asc_gs08_v1.0_c2h2.

### 🎲 Radis version

0.13.0

### 💻 Operating system

MacOS

**Comment by TranHuuNhatHuy** [comment]
Hi @suzil , I ran the script above and it worked normally, fetching all the molecules in the list (except ones I already had, which is perfect as intended).

I also attempted to run a quick check of `DataSource.open(url_above)`, worked fine.

```python
from numpy import DataSource

ds = DataSource()

ds.open("https://aeris-geisa.ipsl.fr/geisa_files/2020/Lines/line_GEISA2020_asc_gs08_v1.0_c2h2")
```

I'm using Windows 10, but during the last RADIS workshop on May 18, the GEISA fetch also worked normally on a wide range of devices. Thus, I suspect this might come from your side. For now, could you run this script again? Or try to delete the GEISA local database and run it again.

What do you think, Mr. @erwanp ?

**Comment by suzil** [comment]
I created a standalone virtual environment and installed numpy (without radis) and I can still reproduce the error. This looks a little suspicious:

```ipython
In [1]: from numpy import DataSource

In [2]: ds = DataSource()

In [3]: ds.exists("https://www.google.com/index.html")
Out[3]: True

In [4]: ds.exists("https://aeris-geisa.ipsl.fr/geisa_files/2020/Lines/line_GEISA
   ...: 2020_asc_gs08_v1.0_c2h2")
Out[4]: False
```

I looked at the [source code for `exists`](https://github.com/numpy/numpy/blob/145ed90f638c1a12ce5b06e9100421f99783f431/numpy/lib/_datasource.py#L479) and I get a better error message

```py
urlopen("https://aeris-geisa.ipsl.fr/geisa_files/2020/Lines/line_GEISA2020_asc_gs08_v1.0_c2h2")
```
```
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
```

Looks like I have some issue with the SSL certificate on my computer.

Based on this [SO answer](https://stackoverflow.com/a/42107877), I ran ` /Applications/Python\ 3.9/Install\ Certificates.command`. And now it works!
