### ISSUE TITLE
todo: add quick-fix for unlabelled HITEMP lines

### ISSUE THREAD

**Issue by erwanp** [radis/radis#509]
### 💭 Description

HITEMP-CO2 has some unlabelled lines; therefore the following non-eq calculations won't work : 

```python
from radis import calc_spectrum
calc_spectrum(2000, 3000,
              molecule='CO2',
              Trot=3000,
              isotope=1,
              Tvib=(3000, 3000, 1000),
              databank='hitemp')
```

RADIS already suggests the user a fix, which requires to use SpectrumFactory : 

```
using HITEMP2010 for CO2, some lines are unlabelled and therefore cannot be used at equilibrium. This is a known issue of the HITEMP database and will soon be fixed in the edition. In the meantime you can use:
 'sf.df0.drop(sf.df0.index[sf.df0['v1u']==-1], inplace=True)' where 'sf' is SpectrumFactory object
```
See https://github.com/radis/radis/issues/508 for an example of where it's used 

It works but requires to change the user script. Would be better if an option was added in `calc_spectrum()` to automatically fix this. 

## Implementation

- let's not declare a new parameter in calc_spectrum ; it would add more info for too few use-cases;  instead let's make it a "secret" parameter: look-up if there is a key in ``kwargs`` 
```
drop_unlabelled_CO2_hitemp_lines=kwargs.pop("drop_unlabelled_CO2_hitemp_lines", False) #  False is the default value 
```

Then add this in calc_spectrum code : 
```
if drop_unlabelled_CO2_hitemp_lines: 
    sf.df0.drop(sf.df0.index[sf.df0['v1u']==-1], inplace=True)
```

and also update the suggested tip in the error message (wherever it is) : 
``` 
using HITEMP2010 for CO2, some lines are unlabelled and therefore cannot be used at equilibrium. This is a known issue of the HITEMP database and will soon be fixed in the edition. In the meantime you can use:
 'sf.df0.drop(sf.df0.index[sf.df0['v1u']==-1], inplace=True)' where 'sf' is SpectrumFactory object ;   or use `calc_spectrum(..., drop_unlabelled_CO2_hitemp_lines=True)` 
```

**Comment by Prtm2110** [comment]
Hello, I tried running the script provided. It asked for credentials for HiTRAN, so I created an account, and now it is downloading files—nearly about 6.1 GB. Is this supposed to happen?

**Comment by minouHub** [comment]
It is a known problem since HITRAN updated the CO2 file in January. Running this test will take you 2-3 hours. A solution is proposed there in one GSOC https://openastronomy.org/gsoc/gsoc2025/#/projects?project=fast_parsing_of_large_databases_and_execution_bottlenecks and a solution is proposed here https://github.com/radis/radis/issues/510#issuecomment-2037688815

**Comment by Prtm2110** [comment]
Hi, I was facing download issues so I have downloaded the 6 GB CO2 Dataset `02_HITEMP2024.par.bz2` directly from HITEMP website, I first need to convert it into hdf5 using `hit2df` right? Where should I store it in `.db`? Could you please let me know the file structure for the corresponding `.hf` file?

**Comment by minouHub** [comment]
The expression `is not able` does not help. I was able to convert it to an hdf5 file but it took 2-3 hours as stated above. I think that sorting the fast parsing issue is a more pressing problem than the one in this issue (we lived well with it since 2022).

**Comment by Prtm2110** [comment]
Sorry for that, I should have been more explicit. When using `hit2df` on the decompressed CO2 dataset, I am facing this error.

```python
import time
from radis.api.hitranapi import hit2df

start_time = time.time()  

df = hit2df("02_HITEMP2024.par") # 50 GB file 

end_time = time.time()  
elapsed_time = end_time - start_time

print(f"Execution Time: {elapsed_time:.2f} seconds")
```
```
(radis) xoein@xoeinXD:/media/xoein/6EC4AEE8C4AEB1AF/Benchmarking$ python3 hit2def_parsing_benchmark.py 
Traceback (most recent call last):
  File "/media/xoein/6EC4AEE8C4AEB1AF/Benchmarking/hit2def_parsing_benchmark.py", line 6, in <module>
    df = hit2df("02_HITEMP2024.par")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xoein/Desktop/THERADIS/radis/radis/api/hitranapi.py", line 273, in hit2df
    df = parse_hitran_file(fname, columns, output=output)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xoein/Desktop/THERADIS/radis/radis/api/tools.py", line 66, in parse_hitran_file
    data = _read_hitran_file(fname, columns, count, linereturnformat)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xoein/Desktop/THERADIS/radis/radis/api/tools.py", line 154, in _read_hitran_file
    return np.fromfile(fname, dtype=dt, count=count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy._core._exceptions._ArrayMemoryError: Unable to allocate 48.9 GiB for an array with shape (326260084,) and data type [('id', 'S2'), ('iso', 'S1'), ('wav', 'S12'), ('int', 'S10'), ('A', 'S10'), ('airbrd', 'S5'), ('selbrd', 'S5'), ('El', 'S10'), ('Tdpair', 'S4'), ('Pshft', 'S8'), ('globu', 'S15'), ('globl', 'S15'), ('locu', 'S15'), ('locl', 'S15'), ('ierr', 'S6'), ('iref', 'S12'), ('lmix', 'S1'), ('gp', 'S7'), ('gpp', 'S7'), ('_linereturn', 'S1')]
```

**Comment by Prtm2110** [comment]
> More generally, I think that sorting the "fast parsing" issue presented in [this comment](https://github.com/radis/radis/issues/510#issuecomment-2037688815) is a more pressing problem.

Yes, I was trying to tackle [Fast Parsing](https://github.com/radis/radis/issues/510). Sorry for the confusion maybe I should have commented in #510 itself.

**Comment by minouHub** [comment]
Your RAM could be too small. You can probably sort this problem using a dedicated environment on python 3.10. There, radis will use vaex which will require much less RAM

**Comment by Prtm2110** [comment]
I have 24 GB DDR4 Ram is it  too small in this case? Also the file is around 48 GB that is possible right?
I tried installing pip version on a fresh python=3.10 env 
```
(radis310) xoein@xoeinXD:/media/xoein/6EC4AEE8C4AEB1AF/Benchmarking$ python3 hit2def_parsing_benchmark.py 

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/media/xoein/6EC4AEE8C4AEB1AF/Benchmarking/hit2def_parsing_benchmark.py", line 2, in <module>
    from radis.api.hitranapi import hit2df
  File "/home/xoein/miniconda3/envs/radis310/lib/python3.10/site-packages/radis/__init__.py", line 234, in <module>
    from . import api, db, io, lbl, los, misc, phys, spectrum, tools
  File "/home/xoein/miniconda3/envs/radis310/lib/python3.10/site-packages/radis/lbl/__init__.py", line 6, in <module>
    from . import bands, base, broadening, calc, factory, labels, loader, overp
  File "/home/xoein/miniconda3/envs/radis310/lib/python3.10/site-packages/radis/lbl/bands.py", line 55, in <module>
    from radis.lbl.broadening import BroadenFactory
  File "/home/xoein/miniconda3/envs/radis310/lib/python3.10/site-packages/radis/lbl/broadening.py", line 93, in <module>
    import vaex
  File "/home/xoein/miniconda3/envs/radis310/lib/python3.10/site-packages/vaex/__init__.py", line 45, in <module>
    import vaex.dataframe
  File "/home/xoein/miniconda3/envs/radis310/lib/python3.10/site-packages/vaex/dataframe.py", line 30, in <module>
    import vaex.grids
  File "/home/xoein/miniconda3/envs/radis310/lib/python3.10/site-packages/vaex/grids.py", line 3, in <module>
    import vaex.vaexfast
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/media/xoein/6EC4AEE8C4AEB1AF/Benchmarking/hit2def_parsing_benchmark.py", line 6, in <module>
    df = hit2df("02_HITEMP2024.par")
  File "/home/xoein/miniconda3/envs/radis310/lib/python3.10/site-packages/radis/api/hitranapi.py", line 273, in hit2df
    df = parse_hitran_file(fname, columns, output=output)
  File "/home/xoein/miniconda3/envs/radis310/lib/python3.10/site-packages/radis/api/tools.py", line 66, in parse_hitran_file
    data = _read_hitran_file(fname, columns, count, linereturnformat)
  File "/home/xoein/miniconda3/envs/radis310/lib/python3.10/site-packages/radis/api/tools.py", line 149, in _read_hitran_file
    return np.fromfile(fname, dtype=dt, count=count)
numpy._core._exceptions._ArrayMemoryError: Unable to allocate 48.9 GiB for an array with shape (326260084,) and data type [('id', 'S2'), ('iso', 'S1'), ('wav', 'S12'), ('int', 'S10'), ('A', 'S10'), ('airbrd', 'S5'), ('selbrd', 'S5'), ('El', 'S10'), ('Tdpair', 'S4'), ('Pshft', 'S8'), ('globu', 'S15'), ('globl', 'S15'), ('locu', 'S15'), ('locl', 'S15'), ('ierr', 'S6'), ('iref', 'S12'), ('lmix', 'S1'), ('gp', 'S7'), ('gpp', 'S7'), ('_linereturn', 'S1')]
```

**Comment by minouHub** [comment]
Back to the initial problem, @erwanp I think this is fine to have this kind of error message. The user must understand what is done to its database (even though these will probably be minor for all cases). Waiting for you opinion but I would prefer to not implement this suggestion.

**Comment by minouHub** [comment]
Closing because inactive

**Comment by prathamhole14** [comment]
Since my previous work allows this to be fixed now: please check https://github.com/radis/radis/pull/1026

**Comment by minouHub** [comment]
I'm sorry but I'm going to re-close this issue and your PR for the following reason:

> The user must understand what is done to its database. 

Adding another argument to `calc_spectrum`, which is already too furnished, is not the philosophie I want to pursue. `calc_spectrum` should be simple. This option is not really needed and the error message provides a clear instruction on what must be done. Since @erwanp did not defend his idea, I prefer to force the user to copy-paste one line and at least we are sure everybody is well aware of what is done :)
