### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by erwanp** [radis/radis#545]
### 🐛 Describe the bug

Docs are broken : https://readthedocs.org/projects/radis/builds/19302835/ 

Apparently due to missing test file : `FileNotFoundError: Test file `trimmed_1857_VoigtCO_Minesi.mat` does not exist`

```

Extension error:
Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/develop/examples/plot_compare_CO_geisa_hitran.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/develop/examples/plot_compare_CO_geisa_hitran.py", line 37, in <module>
    s_geisa = calc_spectrum(**conditions, databank="geisa", name="GEISA's CO")
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/develop/lib/python3.8/site-packages/radis/lbl/calc.py", line 534, in calc_spectrum
    generated_spectrum = _calc_spectrum_one_molecule(
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/develop/lib/python3.8/site-packages/radis/lbl/calc.py", line 800, in _calc_spectrum_one_molecule
    sf.fetch_databank(**conditions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/develop/lib/python3.8/site-packages/radis/lbl/loader.py", line 1364, in fetch_databank
    df, local_paths = fetch_geisa(
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/develop/lib/python3.8/site-packages/radis/io/geisa.py", line 174, in fetch_geisa
    df = ldb.load(
TypeError: load() got an unexpected keyword argument 'isotope'


/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/develop/examples/plot_newfitting_Tgas-molfrac.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/develop/examples/plot_newfitting_Tgas-molfrac.py", line 35, in <module>
    data = scipy.io.loadmat(getTestFile(data_file), simplify_cells=True)["CO_resu_Voigt"]
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/develop/lib/python3.8/site-packages/radis/test/utils.py", line 77, in getTestFile
    raise FileNotFoundError(
FileNotFoundError: Test file `trimmed_1857_VoigtCO_Minesi.mat` does not exist. Choose one of: 
- hitran_CO_fragment.par
- geisa_CO2_fragment.par
- co2_cdsd_hamiltonian_fragment.levels
- CO_Tgas1500K_mole_fraction0.01.spec
- geisa_CO_fragment.par
- hitran_co2_626_bandhead_4165_4200nm.par
- hitran_co_3iso_2000_2300cm.h5
- cdsd_hitemp_09_fragment.txt
- geisa_O2_fragment.par
- calc_N2C_spectrum_Trot1200_Tvib3000_slit0.1.txt
- synth-NH3-1-500-2000cm-P10-mf0.01-p1.spec
- hitran_co2_626_bandhead_4165_4200nm.h5
- CO_Tgas1500K_mole_fraction0.5.spec
- Corentin_0_100cm_DownSampled_20cm_10pctCO2_1-wc-gw450-gr300-sl1500-acc5000-.spec
- hitran_2016_H2O_2iso_2000_2100cm.par
- hitran_co_3iso_2000_2300cm.par
- hitran_CO2_fragment.par
- geisa_H2O_fragment.par
- N2C_specair_380nm.spec
- CO2abscoeff_300K_4150_4400nm.txt
- slitfunction.txt
- cdsd_hitemp_09_fragment.h5
- CO2_measured_spectrum_4-5um.spec
- cdsd_hitemp_09_header.txt
- SpecDatabase_Test
- calc_N2C_spectrum_Trot1200_Tvib3000.txt or use force=True
```

### 💡 Possible solutions

@TranHuuNhatHuy you added this test file  (it does appear in https://github.com/radis/radis/tree/develop/radis/test/files ) . However to appear in the Docs it should also be included in the [MANIFEST.in](https://github.com/radis/radis/blob/develop/MANIFEST.in) file. 

Easy fix

### 🎲 Radis version

latest 

### 💻 Operating system

Windows

---

## Error 2 

There is also another error : 

```

Unexpected failing examples:
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/develop/examples/plot_compare_CO_geisa_hitran.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/develop/examples/plot_compare_CO_geisa_hitran.py", line 37, in <module>
    s_geisa = calc_spectrum(**conditions, databank="geisa", name="GEISA's CO")
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/develop/lib/python3.8/site-packages/radis/lbl/calc.py", line 534, in calc_spectrum
    generated_spectrum = _calc_spectrum_one_molecule(
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/develop/lib/python3.8/site-packages/radis/lbl/calc.py", line 800, in _calc_spectrum_one_molecule
    sf.fetch_databank(**conditions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/develop/lib/python3.8/site-packages/radis/lbl/loader.py", line 1364, in fetch_databank
    df, local_paths = fetch_geisa(
  File "/home/docs/checkouts/readthedocs.org/user_builds/radis/envs/develop/lib/python3.8/site-packages/radis/io/geisa.py", line 174, in fetch_geisa
    df = ldb.load(
TypeError: load() got an unexpected keyword argument 'isotope'
```

**Comment by erwanp** [comment]
@TranHuuNhatHuy can you have a look ?

**Comment by erwanp** [comment]
@TranHuuNhatHuy any update?

**Comment by erwanp** [comment]
@TranHuuNhatHuy untagging you here ; feel free to re-join if you have more time.

**Comment by andreyscott** [comment]
@erwanp  I can, and I'm currently working on this please tag me

**Comment by erwanp** [comment]
Thank you!

**Comment by andreyscott** [comment]
The way I see it I think the error comes from the hdf5.py file 
in the file named geisa.py isotopes is being called but 
the load function got passed an empty array
<img width="407" alt="gso26" src="https://user-images.githubusercontent.com/62455784/227779382-54a2eb57-600a-4f34-99ba-40b829024ea0.PNG">

I think that substituting the argument
`        within=[("iso", Isotope.split(","))],`
 would solve the problem but I would also love to hear what you think

**Comment by erwanp** [comment]
Try it open a PR. If tests pass  it's fine!

**Comment by andreyscott** [comment]
opened

**Comment by erwanp** [comment]
Apparently still failing
```
AttributeError: type object 'Isotope' has no attribute 'split'
```

**Comment by imperorrp** [comment]
I was checking out this issue due to experiencing this same error-

> Apparently still failing
> 
> ```
> AttributeError: type object 'Isotope' has no attribute 'split'
> ```

In line 280 of hdf5.py- `within=[("iso", Isotope.split(","))],` -it seems like the 'Isotope' class is being attempted to be split() like a string would, into a list. 

@andreyscott Was your intention to retrieve something like the Isotope class attribute names, separated into a list?

**Comment by andreyscott** [comment]
@imperorrp yeah sorry about that I thought I had fixed it. I will take into account your comment and walk towards a solution. truly appreciate the input. and if there's anything else please feel free to let me know

**Comment by erwanp** [comment]
I've currently reverted the changes, you can fix the docs locally and test with the docs/gendocs.sh script

**Comment by andreyscott** [comment]
Ok I'm on it

**Comment by andreyscott** [comment]
@erwanp 
I noticed that in Manifest.in file the following include radis/test/files/*.txt, .spec, .par, and .levels, but this one is .mat was not added which would explain this statement trimmed_1857_VoigtCO_Minesi.mat does not exist

Basically I think `include radis/test/files/*.mat` should be added in the manifest

**Comment by minouHub** [comment]
Hello,
The docs are still not compiling. The current error message is:
```
Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x7faeea650940> for event 'builder-inited' threw an exception (exception: no module named radis)
Failed to import radis.
Possible hints:
* ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
* KeyError: 'radis'
```
see more at https://readthedocs.org/projects/radis/builds/21118065/

**Comment by minouHub** [comment]
Sadly, PR #591 didn't sort the issue. See the details of this build on the develop branch: [link here](https://readthedocs.org/projects/radis/builds/21453774/).

**Comment by erwanp** [comment]
Being sorted in a dedicated branch #595
