### ISSUE TITLE
Import CH3 via Exomol

### ISSUE THREAD

**Issue by saradelahaie** [radis/radis#623]
### 🐛 Describe the bug

When computing a CH3 spectrum from exomol database, it doesn't work (while it's working just fine for CH and C2).

```
from radis import calc_spectrum
s = calc_spectrum(
    5000,
    10000,  # cm-1
    molecule="CH3",
    isotope='1',
    pressure=1.01325,  # bar
    Tgas=1000,  # K
    mole_fraction=0.1,
    path_length=1,  # cm
    broadening_method="fft",  # @ dev: Doesn't work with 'voigt'
    databank=("exomol"),  # Simply use 'exomol' for the recommended database
)
```
The prompt is as follows:
```
Using ExoMol database AYYJ for 12C-1H3 (recommended by the ExoMol team). All available databases are ['xsec-AYYJ', 'AYYJ']. Select one of them with `radis.fetch_exomol(DATABASE_NAME)`, `SpectrumFactory.fetch_databank('exomol', exomol_database=DATABASE_NAME')`, or `calc_spectrum(..., databank=('exomol', DATABASE_NAME))` 

Background atmosphere:  Air
Downloading http://www.exomol.com/db/CH3/12C-1H3/12C-1H3__H2.broad and saving as /home/sarad/.radisdb/exomol/CH3/12C-1H3/AYYJ/12C-1H3__H2.broad
Error: Couldn't download .broad file at http://www.exomol.com/db/CH3/12C-1H3/12C-1H3__H2.broad and save.
Downloading http://www.exomol.com/db/CH3/12C-1H3/12C-1H3__He.broad and saving as /home/sarad/.radisdb/exomol/CH3/12C-1H3/AYYJ/12C-1H3__He.broad
Error: Couldn't download .broad file at http://www.exomol.com/db/CH3/12C-1H3/12C-1H3__He.broad and save.
Downloading http://www.exomol.com/db/CH3/12C-1H3/12C-1H3__air.broad and saving as /home/sarad/.radisdb/exomol/CH3/12C-1H3/AYYJ/12C-1H3__air.broad
Error: Couldn't download .broad file at http://www.exomol.com/db/CH3/12C-1H3/12C-1H3__air.broad and save.
Traceback (most recent call last):
  File "/mnt/c/Users/Sara Delahaie/OneDrive-Centralesupelec/OneDrive - CentraleSupelec/Documents - SPARK/6. R&D/3 - Projet Analyse EXPE par thème L1/spectro_emission_IR/230906/find_species_IR.py", line 53, in <module>
    s = calc_spectrum(
  File "/home/sarad/.local/lib/python3.10/site-packages/radis/lbl/calc.py", line 534, in calc_spectrum
    generated_spectrum = _calc_spectrum_one_molecule(
  File "/home/sarad/.local/lib/python3.10/site-packages/radis/lbl/calc.py", line 800, in _calc_spectrum_one_molecule
    sf.fetch_databank(**conditions)
  File "/home/sarad/.local/lib/python3.10/site-packages/radis/lbl/loader.py", line 1298, in fetch_databank
    df, local_path, Z_exomol = fetch_exomol(
  File "/home/sarad/.local/lib/python3.10/site-packages/radis/io/exomol.py", line 207, in fetch_exomol
    mdb = MdbExomol(
  File "/home/sarad/.local/lib/python3.10/site-packages/radis/api/exomolapi.py", line 1275, in __init__
    molec + "__" + dic_def["numtag"][i] + ".trans.bz2"
IndexError: list index out of range
```

### 🎲 Radis version

0.14

### 💻 Operating system

Windows

**Comment by minouHub** [comment]
Hello,
This code worked for me:
```python
from radis import calc_spectrum

s = calc_spectrum(3200, 3300,         # cm-1
                  molecule='CH3',
                  isotope='1',
                  pressure=1.01325,   # bar
                  Tgas=1000,
                  mole_fraction=0.1,
                  databank='exomol',  # or 'hitemp'
                  diluent = "air"     # or {'CO2': 0.1, 'air':0.8}
                  )
s.plot('absorbance')
```
I also tried yours with the 3200-3300 cm-1 range and I had no problem. I believe that the large waverange is the root of the problem?

**Comment by minouHub** [comment]
I am closing the issue because the problem seems to be solved.
