### ISSUE TITLE
Radis potentially incompatible with Numpy 2.0

### ISSUE THREAD

**Issue by minouHub** [radis/radis#686]
### 🐛 Describe the bug

The tests were not passing until we restricted the numpy version to `numpy<2.0`, see [8c97a0a](https://github.com/radis/radis/pull/676/commits/8c97a0ac745f8fb03b625f81bbcc2d3c629b6e3b) in #676. Numpy 2.0 was released today (August 19th) on [conda-forge](https://anaconda.org/conda-forge/numpy) and will probably be followed by [conda](https://anaconda.org/anaconda/numpy) soon.

### 💡 Possible solutions

Read migration guide: https://numpy.org/doc/stable/numpy_2_0_migration_guide.html#numpy-2-migration-guide

### 🎲 Radis version

0.15.1

### 💻 Operating system

Linux

**Comment by arunavabasucom** [comment]
@erwanp pls take a look at this . Link - https://github.com/conda-forge/radis-feedstock/pull/3

**Comment by minouHub** [comment]
FYI, In 0.15.1, I enforced `numpy<2.0` in #684. Not the best but at least it ensures it will be working on pip. 

As I understand conda-forge will be forcing `radis 0.15` to have `numpy 2.0`? Could you confirm?

**Comment by arunavabasucom** [comment]
@minouHub , i am taking to look on that .

**Comment by minouHub** [comment]
I started an environment with numpy 2.0, then ran `conda install radis==0.15 -c conda-forge`. In the output below, near the end, conda forces the version to be numpy=1.26, so there is no problem with `radis=0.15`.
```

(numpy20) PS C:\Users\Nicolas Minesi\Python> conda install radis==0.15 -c conda-forge
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Nicolas Minesi\anaconda3\envs\numpy20

  added / updated specs:
    - radis==0.15


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    astropy-iers-data-0.2024.8.19.0.32.16|     pyhd8ed1ab_0         1.1 MB  conda-forge
    configparser-7.1.0         |     pyhd8ed1ab_0          22 KB  conda-forge
    cython-3.0.11              |  py312h275cf98_0         3.1 MB  conda-forge
    importlib_resources-6.4.3  |     pyhd8ed1ab_0          31 KB  conda-forge
    lxml-5.3.0                 |  py312h53bce91_0         1.0 MB  conda-forge
    m2w64-gcc-libgfortran-5.3.0|                6         342 KB  conda-forge
    m2w64-gcc-libs-5.3.0       |                7         520 KB  conda-forge
    m2w64-gcc-libs-core-5.3.0  |                7         214 KB  conda-forge
    m2w64-gmp-6.1.0            |                2         726 KB  conda-forge
    m2w64-libwinpthread-git-5.0.0.4634.697f757|                2          31 KB  conda-forge
    matplotlib-base-3.9.2      |  py312h90004f6_0         7.4 MB  conda-forge
    msys2-conda-epoch-20160418 |                1           3 KB  conda-forge
    peakutils-1.3.5            |     pyhd8ed1ab_0          13 KB  conda-forge
    pywin32-ctypes-0.2.3       |  py312h2e8e312_0          56 KB  conda-forge
    radis-0.15                 |  py312hd2403df_0         5.3 MB  conda-forge
    scipy-1.14.0               |  py312h1f4e10d_2        15.2 MB  conda-forge
    zipp-3.20.0                |     pyhd8ed1ab_0          20 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        35.0 MB

The following NEW packages will be INSTALLED:

  asteval            conda-forge/noarch::asteval-1.0.2-pyhd8ed1ab_0
  astropy            conda-forge/win-64::astropy-6.1.2-py312h1a27103_0
  astropy-iers-data  conda-forge/noarch::astropy-iers-data-0.2024.8.19.0.32.16-pyhd8ed1ab_0
  astroquery         conda-forge/noarch::astroquery-0.4.7-pyhd8ed1ab_0
  asttokens          conda-forge/noarch::asttokens-2.4.1-pyhd8ed1ab_0
  backports          conda-forge/noarch::backports-1.0-pyhd8ed1ab_4
  backports.tarfile  conda-forge/noarch::backports.tarfile-1.0.0-pyhd8ed1ab_1
  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.12.3-pyha770c72_0
  blosc              conda-forge/win-64::blosc-1.21.6-h85f69ea_0
  brotli             conda-forge/win-64::brotli-1.1.0-hcfcfb64_1
  brotli-bin         conda-forge/win-64::brotli-bin-1.1.0-hcfcfb64_1
  brotli-python      conda-forge/win-64::brotli-python-1.1.0-py312h53d5487_1
  c-blosc2           conda-forge/win-64::c-blosc2-2.15.1-hb461149_0
  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
  certifi            conda-forge/noarch::certifi-2024.7.4-pyhd8ed1ab_0
  cffi               conda-forge/win-64::cffi-1.17.0-py312h4389bb4_0
  charset-normalizer conda-forge/noarch::charset-normalizer-3.3.2-pyhd8ed1ab_0
  configparser       conda-forge/noarch::configparser-7.1.0-pyhd8ed1ab_0
  contourpy          conda-forge/win-64::contourpy-1.2.1-py312h0d7def4_0
  cycler             conda-forge/noarch::cycler-0.12.1-pyhd8ed1ab_0
  cython             conda-forge/win-64::cython-3.0.11-py312h275cf98_0
  decorator          conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0
  dill               conda-forge/noarch::dill-0.3.8-pyhd8ed1ab_0
  executing          conda-forge/noarch::executing-2.0.1-pyhd8ed1ab_0
  fonttools          conda-forge/win-64::fonttools-4.53.1-py312h4389bb4_0
  freetype           conda-forge/win-64::freetype-2.12.1-hdaf720e_2
  future             conda-forge/noarch::future-1.0.0-pyhd8ed1ab_0
  h2                 conda-forge/noarch::h2-4.1.0-pyhd8ed1ab_0
  h5py               conda-forge/win-64::h5py-3.11.0-nompi_py312ha036244_102
  habanero           conda-forge/noarch::habanero-1.2.6-pyhca7485f_0
  hdf5               conda-forge/win-64::hdf5-1.14.3-nompi_h2b43c12_105
  hjson-py           conda-forge/noarch::hjson-py-3.1.0-pyhd8ed1ab_0
  hpack              conda-forge/noarch::hpack-4.0.0-pyh9f0ad1d_0
  html5lib           conda-forge/noarch::html5lib-1.1-pyh9f0ad1d_0
  hyperframe         conda-forge/noarch::hyperframe-6.0.1-pyhd8ed1ab_0
  idna               conda-forge/noarch::idna-3.7-pyhd8ed1ab_0
  importlib-metadata conda-forge/noarch::importlib-metadata-8.2.0-pyha770c72_0
  importlib_metadata conda-forge/noarch::importlib_metadata-8.2.0-hd8ed1ab_0
  importlib_resourc~ conda-forge/noarch::importlib_resources-6.4.3-pyhd8ed1ab_0
  ipython            conda-forge/noarch::ipython-8.26.0-pyh7428d3b_0
  jaraco.classes     conda-forge/noarch::jaraco.classes-3.4.0-pyhd8ed1ab_1
  jaraco.context     conda-forge/noarch::jaraco.context-5.3.0-pyhd8ed1ab_1
  jaraco.functools   conda-forge/noarch::jaraco.functools-4.0.0-pyhd8ed1ab_0
  jedi               conda-forge/noarch::jedi-0.19.1-pyhd8ed1ab_0
  joblib             conda-forge/noarch::joblib-1.4.2-pyhd8ed1ab_0
  json_tricks        conda-forge/noarch::json_tricks-3.17.3-pyhd8ed1ab_0
  keyring            conda-forge/noarch::keyring-25.3.0-pyh7428d3b_0
  kiwisolver         conda-forge/win-64::kiwisolver-1.4.5-py312h0d7def4_1
  krb5               conda-forge/win-64::krb5-1.21.3-hdf4eb48_0
  lcms2              conda-forge/win-64::lcms2-2.16-h67d730c_0
  lerc               conda-forge/win-64::lerc-4.0.0-h63175ca_0
  libaec             conda-forge/win-64::libaec-1.1.3-h63175ca_0
  libbrotlicommon    conda-forge/win-64::libbrotlicommon-1.1.0-hcfcfb64_1
  libbrotlidec       conda-forge/win-64::libbrotlidec-1.1.0-hcfcfb64_1
  libbrotlienc       conda-forge/win-64::libbrotlienc-1.1.0-hcfcfb64_1
  libcurl            conda-forge/win-64::libcurl-8.9.1-h18fefc2_0
  libdeflate         conda-forge/win-64::libdeflate-1.21-h2466b09_0
  libjpeg-turbo      conda-forge/win-64::libjpeg-turbo-3.0.0-hcfcfb64_1
  libpng             conda-forge/win-64::libpng-1.6.43-h19919ed_0
  libssh2            conda-forge/win-64::libssh2-1.11.0-h7dfc565_0
  libtiff            conda-forge/win-64::libtiff-4.6.0-hb151862_4
  libwebp-base       conda-forge/win-64::libwebp-base-1.4.0-hcfcfb64_0
  libxcb             conda-forge/win-64::libxcb-1.16-hcd874cb_0
  libxslt            conda-forge/win-64::libxslt-1.1.39-h3df6e99_0
  llvmlite           conda-forge/win-64::llvmlite-0.43.0-py312h1f7db74_0
  lmfit              conda-forge/noarch::lmfit-1.3.2-pyhd8ed1ab_0
  lxml               conda-forge/win-64::lxml-5.3.0-py312h53bce91_0
  lz4-c              conda-forge/win-64::lz4-c-1.9.4-hcfcfb64_0
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.9.2-py312h90004f6_0
  matplotlib-inline  conda-forge/noarch::matplotlib-inline-0.1.7-pyhd8ed1ab_0
  more-itertools     conda-forge/noarch::more-itertools-10.4.0-pyhd8ed1ab_0
  mpldatacursor      conda-forge/noarch::mpldatacursor-0.7.1-pyhd8ed1ab_0
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0
  numba              conda-forge/win-64::numba-0.60.0-py312hcccf92d_0
  numexpr            conda-forge/win-64::numexpr-2.10.0-mkl_py312h295738f_0
  openjpeg           conda-forge/win-64::openjpeg-2.5.2-h3d672ee_0
  pandas             conda-forge/win-64::pandas-2.2.2-py312h72972c8_1
  parso              conda-forge/noarch::parso-0.8.4-pyhd8ed1ab_0
  patsy              conda-forge/noarch::patsy-0.5.6-pyhd8ed1ab_0
  peakutils          conda-forge/noarch::peakutils-1.3.5-pyhd8ed1ab_0
  pickleshare        conda-forge/noarch::pickleshare-0.7.5-py_1003
  pillow             conda-forge/win-64::pillow-10.4.0-py312h381445a_0
  plotly             conda-forge/noarch::plotly-5.23.0-pyhd8ed1ab_0
  progressbar2       conda-forge/noarch::progressbar2-4.4.2-pyhd8ed1ab_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.47-pyha770c72_0
  psutil             conda-forge/win-64::psutil-6.0.0-py312h4389bb4_0
  pthread-stubs      conda-forge/win-64::pthread-stubs-0.4-hcd874cb_1001
  pure_eval          conda-forge/noarch::pure_eval-0.2.3-pyhd8ed1ab_0
  py-cpuinfo         conda-forge/noarch::py-cpuinfo-9.0.0-pyhd8ed1ab_0
  pycparser          conda-forge/noarch::pycparser-2.22-pyhd8ed1ab_0
  pyerfa             conda-forge/win-64::pyerfa-2.0.1.4-py312h1a27103_1
  pygments           conda-forge/noarch::pygments-2.18.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.1.2-pyhd8ed1ab_0
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyh0701188_6
  pytables           conda-forge/win-64::pytables-3.9.2-py312h3d8899c_3
  python-dateutil    conda-forge/noarch::python-dateutil-2.9.0-pyhd8ed1ab_0
  python-tzdata      conda-forge/noarch::python-tzdata-2024.1-pyhd8ed1ab_0
  python-utils       conda-forge/noarch::python-utils-3.8.2-pyhd8ed1ab_0
  pytz               conda-forge/noarch::pytz-2024.1-pyhd8ed1ab_0
  pyvo               conda-forge/noarch::pyvo-1.5.2-pyhd8ed1ab_0
  pywin32-ctypes     conda-forge/win-64::pywin32-ctypes-0.2.3-py312h2e8e312_0
  pyyaml             conda-forge/win-64::pyyaml-6.0.2-py312h4389bb4_0
  qhull              conda-forge/win-64::qhull-2020.2-hc790b64_5
  radis              conda-forge/win-64::radis-0.15-py312hd2403df_0
  requests           conda-forge/noarch::requests-2.32.3-pyhd8ed1ab_0
  scipy              conda-forge/win-64::scipy-1.14.0-py312h1f4e10d_2
  seaborn            conda-forge/noarch::seaborn-0.13.2-hd8ed1ab_2
  seaborn-base       conda-forge/noarch::seaborn-base-0.13.2-pyhd8ed1ab_2
  setuptools-scm     conda-forge/noarch::setuptools-scm-8.1.0-pyhd8ed1ab_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  snappy             conda-forge/win-64::snappy-1.2.1-h23299a8_0
  soupsieve          conda-forge/noarch::soupsieve-2.5-pyhd8ed1ab_1
  stack_data         conda-forge/noarch::stack_data-0.6.2-pyhd8ed1ab_0
  statsmodels        conda-forge/win-64::statsmodels-0.14.2-py312h1a27103_0
  tenacity           conda-forge/noarch::tenacity-9.0.0-pyhd8ed1ab_0
  termcolor          conda-forge/noarch::termcolor-2.4.0-pyhd8ed1ab_0
  tqdm               conda-forge/noarch::tqdm-4.66.5-pyhd8ed1ab_0
  traitlets          conda-forge/noarch::traitlets-5.14.3-pyhd8ed1ab_0
  typing-extensions  conda-forge/noarch::typing-extensions-4.12.2-hd8ed1ab_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.12.2-pyha770c72_0
  uncertainties      conda-forge/noarch::uncertainties-3.2.2-pyhd8ed1ab_1
  urllib3            conda-forge/noarch::urllib3-2.2.2-pyhd8ed1ab_1
  wcwidth            conda-forge/noarch::wcwidth-0.2.13-pyhd8ed1ab_0
  webencodings       conda-forge/noarch::webencodings-0.5.1-pyhd8ed1ab_2
  win_inet_pton      conda-forge/noarch::win_inet_pton-1.1.0-pyhd8ed1ab_6
  xorg-libxau        conda-forge/win-64::xorg-libxau-1.0.11-hcd874cb_0
  xorg-libxdmcp      conda-forge/win-64::xorg-libxdmcp-1.1.3-hcd874cb_0
  yaml               conda-forge/win-64::yaml-0.2.5-h8ffe710_2
  zipp               conda-forge/noarch::zipp-3.20.0-pyhd8ed1ab_0
  zlib-ng            conda-forge/win-64::zlib-ng-2.2.1-he0c23c2_0
  zstandard          conda-forge/win-64::zstandard-0.23.0-py312h7606c53_0
  zstd               conda-forge/win-64::zstd-1.5.6-h0ea2cb4_0

The following packages will be UPDATED:

  exceptiongroup     pkgs/main/win-64::exceptiongroup-1.2.~ --> conda-forge/noarch::exceptiongroup-1.2.2-pyhd8ed1ab_0
  iniconfig          pkgs/main::iniconfig-1.1.1-pyhd3eb1b0~ --> conda-forge::iniconfig-2.0.0-pyhd8ed1ab_0

The following packages will be SUPERSEDED by a higher-priority channel:

  colorama           pkgs/main/win-64::colorama-0.4.6-py31~ --> conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0
  packaging          pkgs/main/win-64::packaging-24.1-py31~ --> conda-forge/noarch::packaging-24.1-pyhd8ed1ab_0
  tomli              pkgs/main/win-64::tomli-2.0.1-py312ha~ --> conda-forge/noarch::tomli-2.0.1-pyhd8ed1ab_0

The following packages will be DOWNGRADED:

  intel-openmp                       2024.2.1-h57928b3_1083 --> 2023.2.0-h57928b3_50497
  libblas                                3.9.0-23_win64_mkl --> 3.9.0-20_win64_mkl
  libcblas                               3.9.0-23_win64_mkl --> 3.9.0-20_win64_mkl
  liblapack                              3.9.0-23_win64_mkl --> 3.9.0-20_win64_mkl
  mkl                                 2024.1.0-h66d3029_694 --> 2023.2.0-h6a75c08_50497
  numpy                               2.0.0-py312h49bc9c5_0 --> 1.26.4-py312h8753938_0


Proceed ([y]/n)? q
```

**Comment by minouHub** [comment]
There might be a problem with vaex as well:
```
import radis
```
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "C:\Users\Nicolas Minesi\Python\radis\__init__.py", line 234, in <module>
    from . import api, db, io, lbl, los, misc, phys, spectrum, tools
  File "C:\Users\Nicolas Minesi\Python\radis\lbl\__init__.py", line 6, in <module>
    from . import bands, base, broadening, calc, factory, labels, loader, overp
  File "C:\Users\Nicolas Minesi\Python\radis\lbl\bands.py", line 55, in <module>
    from radis.lbl.broadening import BroadenFactory
  File "C:\Users\Nicolas Minesi\Python\radis\lbl\broadening.py", line 93, in <module>
    import vaex
  File "C:\Users\Nicolas Minesi\anaconda3\envs\radis_deploy\lib\site-packages\vaex\__init__.py", line 45, in <module>
    import vaex.dataframe
  File "C:\Users\Nicolas Minesi\anaconda3\envs\radis_deploy\lib\site-packages\vaex\dataframe.py", line 30, in <module>
    import vaex.grids
  File "C:\Users\Nicolas Minesi\anaconda3\envs\radis_deploy\lib\site-packages\vaex\grids.py", line 3, in <module>
    import vaex.vaexfast
AttributeError: _ARRAY_API not found
```
