### ISSUE TITLE
Invalid workarea pointer when calculating H2O using GPU acceleration

### ISSUE THREAD

**Issue by Airfooox** [radis/radis#694]
### 🐛 Describe the bug

This problem occured when trying to simulate hot H2O spectra while using GPU acceleration. Looking at the error I'd assume that the pointer, which points to the workarea in GPU memory, is somehow invalid/null.

The behavior of the error is somewhat difficult to explain. It only occured when having a temperature >~ 1375 °C, but not below it. Also when reducing the wavespace or increasing the wstep, the error did not occur. Therefore I guess that it has something to do with available memory. Maybe the ~16 GB are not enough for the huge H2O data in that desired wavespace.
(If it is indeed hardware memory limitation, I'd suggest handling the error and giving an explanation of what happened - I also know of merging spectra, but I just wanted to make sure this isn't a easily fixable configuration problem or something like that before splitting up the calculations.)

Minimal code that reproduces the error:
```py
import astropy.units as u
from radis import SpectrumFactory

def main():
    kMin, kMax = 2000, 5000
    wstep = 0.005
    pressure = 1.01325  # in bar

    h2oSpectrumFactory = SpectrumFactory(
        kMin * u.k,
        kMax * u.k,
        species='H2O',
        isotope='all',
        self_absorption=True,
        wstep=wstep,  # cm-1
        pressure=pressure,  # bar
        medium='air',
        cutoff=1e-27,
        truncation=50,
        neighbour_lines=50,
        db_use_cached=True,
        lvl_use_cached=True,
        verbose=3
    )
    h2oSpectrumFactory.fetch_databank("hitemp")

    hotGasTemperature = 273.15 + 1600
    hotH2OConcentration = 1 / 100
    hotGasPathLength = 1

    hotH2OSpectrum = h2oSpectrumFactory.eq_spectrum_gpu(
        name="hotH2O-GPU",
        Tgas=hotGasTemperature,
        mole_fraction=hotH2OConcentration,
        path_length=hotGasPathLength,
        exit_gpu=True
    )

if __name__ == '__main__':
    main()
```

with the terminal output:
```
HAPI version: 1.2.2.2
/home/airfoxxx/.local/share/virtualenvs/Radis-Simulator-KzESAA_5/lib/python3.11/site-packages/radis/lbl/factory.py:1179: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  molarmass_arr[iso] = params.molar_mass
... 0.00s - Generated Wavenumber Arrays
... Scaling equilibrium linestrength
... 0.66s - Scaled equilibrium linestrength
Initializing parameters... Number of lines loaded: 28286785

mode: GPU
Copying initialization parameters to device memory...
0 mod.global
size:  100
0 mod.HtoD
Initializing Gaussian parameters
done!
Initializing Lorentzian parameters 
done!
done!
Allocating device memory and copying data...
0 arr.alloc
0x7e33b1400000 4960120
0 arr.alloc
0x7e33b1a00000 4960116
0 arr.alloc
0x7e33fb800000 4960116
0 arr.alloc
0x7e33f6000000 4960120
0 arr.alloc
0x7e33f6600000 4960120
0 arr.alloc
0x7e33f6c00000 4960116
0 arr.alloc
0x7e33d6000000 28286785
0 arr.HtoD
0 arr.alloc
0x7e3322000000 113147140
0 arr.HtoD
0 arr.alloc
0x7e3306000000 113147140
0 arr.HtoD
0 arr.alloc
0x7e32ec000000 113147140
0 arr.HtoD
0 arr.alloc
0x7e32e2000000 113147140
0 arr.HtoD
0 arr.alloc
0x7e32d2000000 226294280
0 arr.HtoD
0 arr.alloc
0x7e32c8000000 113147140
0 arr.HtoD
0 time.create
0 time.create
0 time.record
done!
Initialization complete!
Calculating spectra... Copying iteration parameters to device...
0 time.record
0 mod.global
size:  176
0 mod.HtoD
0 time.record
0 time.sync
0 time.time
done!
Filling LDM...
0 arr.alloc
0x7e324e000000 1741000716
0 arr.zeros
0 func.kernel
0 time.record
0 time.sync
0 time.time
done!
Applying lineshapes...
0 arr.alloc
0x7e31e4000000 1741002120
0 fft.plan create
0 fft.setalloc
0 fft.plan many
2 arr.alloc
0 fft.set workarea
Traceback (most recent call last):
  File "/home/airfoxxx/.local/share/virtualenvs/Radis-Simulator-KzESAA_5/lib/python3.11/site-packages/radis/gpu/cuda/driver.py", line 487, in _getPlan
    return self._plans[self._arr.shape]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: (1240029, 9, 39)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airfoxxx/Radis-Simulator/bug_example_gpu.py", line 42, in <module>
    main()
  File "/home/airfoxxx/Radis-Simulator/bug_example_gpu.py", line 33, in main
    hotH2OSpectrum = h2oSpectrumFactory.eq_spectrum_gpu(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airfoxxx/.local/share/virtualenvs/Radis-Simulator-KzESAA_5/lib/python3.11/site-packages/radis/lbl/factory.py", line 1240, in eq_spectrum_gpu
    abscoeff_calc, iter_params, times = gpu_iterate(
                                        ^^^^^^^^^^^^
  File "/home/airfoxxx/.local/share/virtualenvs/Radis-Simulator-KzESAA_5/lib/python3.11/site-packages/radis/gpu/gpu.py", line 341, in gpu_iterate
    gpu_mod.fft_fwd()
  File "/home/airfoxxx/.local/share/virtualenvs/Radis-Simulator-KzESAA_5/lib/python3.11/site-packages/radis/gpu/cuda/driver.py", line 531, in __call__
    _plan, ptrval = self._getPlan()
                    ^^^^^^^^^^^^^^^
  File "/home/airfoxxx/.local/share/virtualenvs/Radis-Simulator-KzESAA_5/lib/python3.11/site-packages/radis/gpu/cuda/driver.py", line 526, in _getPlan
    self._plans[self._arr.shape] = [_plan, int(self.workarea._ptr.value)]
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

```

on the following hardware (nvidia-smi output):
```
Mon Sep  9 14:35:23 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A4000               Off |   00000000:03:00.0 Off |                  Off |
| 41%   57C    P0             33W /  140W |    1396MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1381      G   /usr/lib/xorg/Xorg                            126MiB |
|    0   N/A  N/A      1563      G   /usr/bin/gnome-shell                            8MiB |
|    0   N/A  N/A     12944      C   ./Radis-Simulator_linux                  1152MiB |
+-----------------------------------------------------------------------------------------+

```
It seems like there is a version of the radis simulator still left in gpu memory because it aborted/died during the calculation.

### 🎲 Radis version

0.15.1

### 💻 Operating system

Linux

**Comment by dcmvdbekerom** [comment]
This indeed sounds like a memory issue. When you increase the temperature, the pressure broadening constants span a larger range, and since the resolution of the pressure broadening is constrained, the required memory increases. You could try to set the pressure broadening resolution to a lower value and see if this resolves your issue.

I agree that, if this is indeed the issue, we should arrange a clearer error message.

That said, the GPU part is still in an early stage and does not receive as much attention because of the extra skills required for programming on GPU.

**Comment by minouHub** [comment]
Hello,
I tried on my laptop (`radis 0.15.1` and Windows 11) and it worked fine. I guess it's because I have 4 GB of memory on my Nvidia. Here is my nvidia-smi output **during** the execution. The processes disappeared after the code was ran. 

```
C:\Windows\System32>nvidia-smi
Tue Sep 10 09:59:32 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.77                 Driver Version: 537.77       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A1000 Laptop GPU  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   59C    P0              15W /  35W |   3904MiB /  4096MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     22296      C   ...aconda3\envs\radis_py310\python.exe    N/A      |
+---------------------------------------------------------------------------------------+
```

So, if I sum up, probably a GPU memory limitation.

- @Airfooox could you try on another computer?
- @dcmvdbekerom, in your PR #624, would it be hard to add a tentative explanation such "Seems your GPU memory reached its limit. See #694 and https://docs.nvidia.com/cuda/archive/10.1/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1gc6c391505e117393cc2558fff6bfc2e9"

**Comment by dcmvdbekerom** [comment]
Possibly related https://stackoverflow.com/questions/72431190/cuda-out-of-memory-when-there-is-plenty-available
Yes adding a warning should be easy

**Comment by dcmvdbekerom** [comment]
CUDA backend is deprecated since the implementation of the Vulkan API. See https://github.com/radis/radis/issues/758 and https://github.com/radis/radis/pull/624.
@Airfooox could you check if the error is still there with the Vulkan API? If so, please open a new issue.

**Comment by Airfooox** [comment]
Thanks for the update. I would check again, but I'm not working at the company anymore where I used radis. :D
