### ISSUE TITLE
DOCUMENTATION TODO LIST

### ISSUE THREAD

**Issue by erwanp** [radis/radis#77]
# List of small documentation improvements

**New contributors**: you may want to pick one of these items and implement it. That's a good start! For that, it is recommended that you first open a [New Issue](https://github.com/radis/radis/issues/new) dedicated to the chosen item! 

**New users**: if a RADIS feature is not clear, comment here and we'll improve the documentation at some point. You can also mention in on the community chat: 

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/radis-radiation/community)

- [ ] [resample](https://radis.readthedocs.io/en/latest/source/radis.spectrum.spectrum.html#radis.spectrum.spectrum.Spectrum.resample) : add examples

**Comment by CorentinGrimaldi** [comment]
Add more examples in Line_survey. Also the link to the online website https://radis.readthedocs.io/en/latest/tools/line_survey.html  doesnt work.

**Comment by adityabharadwaj198** [comment]
The links under "see also" (at the end of the page) don't work.
[here](https://radis.readthedocs.io/en/latest/source/radis.io.query.html)

**Comment by erwanp** [comment]
Added : 

> generalize the use of "opacity", which is according to ISO 80000-7:2019 the same term as our "abscoeff", and more widely used in astrophysics.

**Comment by anandxkumar** [comment]
In the LBL documentation [documentation ](https://radis.readthedocs.io/en/latest/lbl/lbl.html#flow-chart)  this [link](https://radis.readthedocs.io/en/latest/lbl/lbl/RADIS_flow_chart) doesn't exist (Radis Flow Chart) .

**Comment by erwanp** [comment]
Thank you @anandxkumar for reporting. The link is now https://radis.readthedocs.io/en/latest/_images/RADIS_flow_chart.svg .  Do you want to fix it directly ?

**Comment by anandxkumar** [comment]
Hello @erwanp, in the [Features Use Cases section ](https://radis.readthedocs.io/en/latest/features/features.html#use-cases), the comparison image of 2 spectra is not publishing and we are getting the alternate text `https://radis.readthedocs.io/en/latest/_images/cdsd4000_vs_hitemp_3409K.svg`, should I create a new pull request solving both issues by changing `.. image:: spectrum/cdsd4000_vs_hitemp_3409K.*` to image link in `features.rst ` and similar for the LBL documentation?

**Comment by erwanp** [comment]
Hello. The `cdsd4000_vs_hitemp_3409K` image you're referring to also appears in the main index : https://radis.readthedocs.io/en/latest/index.html   .  Here, it renders properly. You may use the code there to fix it. 

However, it does not appear in the [pdf documentation](https://radis.readthedocs.io/_/downloads/en/latest/pdf/ ) . You may want to investigate why. 

Images rendering are a bit of a pain in Readthedocs. If you want to work on this, you should try to build the docs locally. See [gendocs.sh](https://github.com/radis/radis/blob/develop/docs/gendocs.sh)

**Comment by anandxkumar** [comment]
Made a pull request for the same. Not sure why the images weren't rendering. The exact same code runs fine on 1 file and not on the other(tried replicating 1 working .rst file into the other to see if it work but negative). It worked fine when I loaded the image link. One suggestion, can we add a documentation for contributing to the radis document so that  if anyone wants to contribute to it as a Good First Issue can refer to it( like installing the necessary sphinx library, running `./gendocs.sh`, checking `docs/_build/html/index.html` to see the changes) ?

Also can you help me with one issue I'm facing due to the documentation thing. After running `./gendocs.sh`, whenever I run `pytest`, in the beginning I get this error 
```
platform linux -- Python 3.6.13, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/pipebomb/radis, configfile: setup.cfg
collected 168 items / 13 deselected / 155 selected                             

docs/_build/html/_sources/dev/test.rst.txt F                             [  0%]
```
Following is the traceback - 
<details>
<summary>Traceback</summary>
____________________________ [doctest] test.rst.txt ____________________________<br>
126 <br>
127 Load a line database file ::<br>
128 <br>
129     from radis.test.utils import getTestFile<br>
130     from radis.io.hitran import hit2df<br>
131     df = hit2df(getTestFile("hitran_CO_fragment.par"))<br>
132 <br>
133     print(df)  # replace with your test code<br>
134 <br>
135     >>> Out:<br>
UNEXPECTED EXCEPTION: SyntaxError('invalid syntax', ('<doctest test.rst.txt[0]>', 1, 5, 'Out:\n'))<br>
Traceback (most recent call last):<br>
  File "/home/pipebomb/anaconda3/envs/radis-env/lib/python3.6/doctest.py", line 1330, in __run<br>
    compileflags, 1), test.globs)<br>
  File "<doctest test.rst.txt[0]>", line 1<br>
    Out:<br>
       ^<br>
SyntaxError: invalid syntax<br>
/home/pipebomb/radis/docs/_build/html/_sources/dev/test.rst.txt:135: UnexpectedException<br>

</details>

But the same passed on Travis CI without any issue. I deleted the .radis, .radisdb but that isn't the issue. Not sure what to do to resolve this. Thanks!

**Comment by AlphaVictorDelta** [comment]
Contributor badge on README.rst has the wrong target (to stargazers)
fixed it in #231

**Comment by AlphaVictorDelta** [comment]
@erwanp I am having a problem pip installing radis.
Installation terminates with this message: 'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.'
Python version: 3.9.2
Could you please help me out?

**Comment by erwanp** [comment]
A new version was released this morning, you're probably one of the first to install it, so it's possible that something broke. Let's discuss this on [Slack](https://github.com/radis/slack-invite) ! @erwan

**Comment by anandxkumar** [comment]
Hi @AlphaVictorDelta , I tried to install on anaconda venv python=3.9.2, and it installed without any issue. You may want to share the whole error script you were facing while installing the same.

**Comment by AlphaVictorDelta** [comment]
@anandxkumar Could you tell me step by step how you installed it on anaconda?
@erwanp I'll try this out. I'll get back to you if it works.

**Comment by anandxkumar** [comment]
You may want to install radis on a virtual environment. You will either be using Anaconda or any other python lib. 
If using Anaconda, simple use the anaconda terminal to create a virtual environment by using `conda create -n radis-env python=3.8 ` then activate the environment and use `pip install radis` to see if it is installing or not. 
But for developer purpose you  may want to fork the repo and clone on your local system and then change directory into radis folder and run the command 
`pip install -e .[dev]` to install packages. If you have simple python installed you may want to to refer to this [link](https://docs.python.org/3/library/venv.html) for creating virtual environment.
It is highly suggested to create an environment similar to the environment.yml file(contains all virtual environment details, like python version, dependencies, etc).
if using anaconda create venv using this code `conda env create -f environment.yml` for creating the environment. Hope this helps :)

**Comment by AlphaVictorDelta** [comment]
@anandxkumar "If using Anaconda, simply use the anaconda terminal to create a virtual environment by using conda create -n radis-env python=3.8 then activate the environment and use pip install radis to see if it is installing or not."
This worked. Thanks a lot.

**Comment by TranHuuNhatHuy** [comment]
Currently the documentation for `fetch_hitran()` [here](https://radis.readthedocs.io/en/latest/source/radis.io.hitran.html#radis.io.hitran.fetch_hitran) features an example of `fetch_hitemp` instead. Not sure if this is deliberate.

**Comment by erwanp** [comment]
It is not deliberate, good catch. You can replace it with fetch_hitran() !

Note 1 : fetch_hitemp() and fetch_exomol() could also be mentionned in the See Also section of fetch_hitran()  (and vice-versa) 

Note 2 : [fetch_hitemp()](https://radis.readthedocs.io/en/latest/source/radis.html#radis.fetch_hitemp) does not mention the Gallery Examples which use it (for instance [this one](https://radis.readthedocs.io/en/latest/auto_examples/plot_hitemp_OH_database.html#sphx-glr-auto-examples-plot-hitemp-oh-database-py)). I think it's because the minigallery command in fetch_hitemp() refers to radis.io.hitemp.fetch_hitemp() although it is geenrated in the doc as radis.fetch_hitemp() 
```
    .. minigallery:: radis.io.hitemp.fetch_hitemp
```
Could be the same for the other fetch_* functions

**Comment by TranHuuNhatHuy** [comment]
@erwanp Your second note perfectly explains why I could not import and use `fetch_hitran()` from `radis` the same way I did with `fetch_hitemp()`. Much oblidged for this. I will put a PR for them soon.

**Comment by erwanp** [comment]
Link to "column_2004" in the download-HITEMP example doesn't work https://radis.readthedocs.io/en/latest/auto_examples/plot_hitemp_OH_database.html#sphx-glr-auto-examples-plot-hitemp-oh-database-py
